// Code generated by wsdl2openapi; DO NOT EDIT.
package demo.demo.colors

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class Color {
  @SerialName("RED")
  Red,
  @SerialName("green-ish")
  GreenIsh,
  @SerialName("Blue")
  Blue,
}
