// Code generated by wsdl2openapi; DO NOT EDIT.

package signatureservice74

import (
	"encoding/xml"
	connectorcommon50 "github.com/test/testproj/kon/soap/de/gematik/ws/conn/connectorcommon50"
	connectorcontext20 "github.com/test/testproj/kon/soap/de/gematik/ws/conn/connectorcontext20"
	core "github.com/test/testproj/kon/soap/oasis/names/tc/dss10/core"
	signaturepolicy "github.com/test/testproj/kon/soap/oasis/names/tc/dssx10/profiles/signaturepolicy"
	verificationreport "github.com/test/testproj/kon/soap/oasis/names/tc/dssx10/profiles/verificationreport"
)

type SignDocument struct {
	XMLName     xml.Name                     `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 SignDocument"`
	CardHandle  connectorcommon50.CardHandle `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	Context     connectorcontext20.Context   `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	TvMode      TvMode                       `xml:"TvMode"`
	JobNumber   *JobNumber                   `xml:"JobNumber,omitempty"`
	SignRequest []SignRequest                `xml:"SignRequest"`
}

type SignRequest struct {
	XMLName        xml.Name `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 SignRequest"`
	RequestID      string   `xml:"RequestID,attr"`
	OptionalInputs *struct {
		XMLName         xml.Name            `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 OptionalInputs"`
		SignatureType   *core.SignatureType `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignatureType,omitempty"`
		Properties      *core.Properties    `xml:"urn:oasis:names:tc:dss:1.0:core:schema Properties,omitempty"`
		IncludeEContent *IncludeEContent    `xml:"IncludeEContent,omitempty"`
		IncludeObjects  *struct {
			XMLName       xml.Name             `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 IncludeObjects"`
			IncludeObject []core.IncludeObject `xml:"urn:oasis:names:tc:dss:1.0:core:schema IncludeObject"`
		} `xml:"IncludeObjects,omitempty"`
		SignaturePlacement           *core.SignaturePlacement                      `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignaturePlacement,omitempty"`
		ReturnUpdatedSignature       *core.ReturnUpdatedSignature                  `xml:"urn:oasis:names:tc:dss:1.0:core:schema ReturnUpdatedSignature,omitempty"`
		Schemas                      *core.Schemas                                 `xml:"urn:oasis:names:tc:dss:1.0:core:schema Schemas,omitempty"`
		GenerateUnderSignaturePolicy *signaturepolicy.GenerateUnderSignaturePolicy `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:SignaturePolicy:schema# GenerateUnderSignaturePolicy,omitempty"`
		ViewerInfo                   *ViewerInfo                                   `xml:"ViewerInfo,omitempty"`
	} `xml:"OptionalInputs,omitempty"`
	Document              Document              `xml:"Document"`
	IncludeRevocationInfo IncludeRevocationInfo `xml:"IncludeRevocationInfo"`
}

type SignatureSchemes string

type DocumentWithSignature struct {
	XMLName    xml.Name         `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 DocumentWithSignature"`
	Id         string           `xml:"ID,attr,omitempty"`
	RefURI     string           `xml:"RefURI,attr,omitempty"`
	RefType    string           `xml:"RefType,attr,omitempty"`
	SchemaRefs string           `xml:"SchemaRefs,attr,omitempty"`
	ShortText  string           `xml:"ShortText,attr,omitempty"`
	Base64XML  string           `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Base64XML,omitempty"`
	Base64Data *core.Base64Data `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data,omitempty"`
}

type SignDocumentResponse struct {
	XMLName      xml.Name       `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 SignDocumentResponse"`
	SignResponse []SignResponse `xml:"SignResponse"`
}

type SignResponse struct {
	XMLName         xml.Name                 `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 SignResponse"`
	RequestID       string                   `xml:"RequestID,attr"`
	Status          connectorcommon50.Status `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	OptionalOutputs *struct {
		XMLName               xml.Name                               `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 OptionalOutputs"`
		DocumentWithSignature *DocumentWithSignature                 `xml:"DocumentWithSignature,omitempty"`
		VerificationReport    *verificationreport.VerificationReport `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# VerificationReport,omitempty"`
	} `xml:"OptionalOutputs,omitempty"`
	SignatureObject *core.SignatureObject `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignatureObject,omitempty"`
}

type VerifyDocument struct {
	XMLName        xml.Name                   `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 VerifyDocument"`
	Context        connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	TvMode         *TvMode                    `xml:"TvMode,omitempty"`
	OptionalInputs *struct {
		XMLName                  xml.Name                                     `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 OptionalInputs"`
		VerifyManifests          string                                       `xml:"VerifyManifests,omitempty"`
		UseVerificationTime      *UseVerificationTime                         `xml:"UseVerificationTime,omitempty"`
		AdditionalKeyInfo        *core.AdditionalKeyInfo                      `xml:"urn:oasis:names:tc:dss:1.0:core:schema AdditionalKeyInfo,omitempty"`
		ReturnVerificationReport *verificationreport.ReturnVerificationReport `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# ReturnVerificationReport,omitempty"`
		Schemas                  *core.Schemas                                `xml:"urn:oasis:names:tc:dss:1.0:core:schema Schemas,omitempty"`
		ViewerInfo               *ViewerInfo                                  `xml:"ViewerInfo,omitempty"`
	} `xml:"OptionalInputs,omitempty"`
	Document              *Document             `xml:"Document,omitempty"`
	SignatureObject       *core.SignatureObject `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignatureObject,omitempty"`
	IncludeRevocationInfo IncludeRevocationInfo `xml:"IncludeRevocationInfo"`
}

type UseVerificationTime struct {
	XMLName        xml.Name `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 UseVerificationTime"`
	CurrentTime    string   `xml:"urn:oasis:names:tc:dss:1.0:core:schema CurrentTime,omitempty"`
	SpecificTime   string   `xml:"urn:oasis:names:tc:dss:1.0:core:schema SpecificTime,omitempty"`
	UnknownContent string
}

type VerifyDocumentResponse struct {
	XMLName            xml.Name                 `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 VerifyDocumentResponse"`
	Status             connectorcommon50.Status `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	VerificationResult VerificationResultType   `xml:"VerificationResult"`
	OptionalOutputs    *struct {
		XMLName               xml.Name                               `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 OptionalOutputs"`
		VerifyManifestResults *core.VerifyManifestResults            `xml:"urn:oasis:names:tc:dss:1.0:core:schema VerifyManifestResults,omitempty"`
		DocumentWithSignature *DocumentWithSignature                 `xml:"DocumentWithSignature,omitempty"`
		UpdatedSignature      *core.UpdatedSignature                 `xml:"urn:oasis:names:tc:dss:1.0:core:schema UpdatedSignature,omitempty"`
		VerificationReport    *verificationreport.VerificationReport `xml:"urn:oasis:names:tc:dss-x:1.0:profiles:verificationreport:schema# VerificationReport,omitempty"`
	} `xml:"OptionalOutputs,omitempty"`
}

type GetJobNumber struct {
	XMLName xml.Name                   `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 GetJobNumber"`
	Context connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
}

type GetJobNumberResponse struct {
	XMLName   xml.Name  `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 GetJobNumberResponse"`
	JobNumber JobNumber `xml:"JobNumber"`
}

type ExternalAuthenticate struct {
	XMLName        xml.Name                     `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 ExternalAuthenticate"`
	CardHandle     connectorcommon50.CardHandle `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	Context        connectorcontext20.Context   `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	OptionalInputs *struct {
		XMLName          xml.Name            `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 OptionalInputs"`
		SignatureType    *core.SignatureType `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignatureType,omitempty"`
		SignatureSchemes *SignatureSchemes   `xml:"SignatureSchemes,omitempty"`
	} `xml:"OptionalInputs,omitempty"`
	BinaryString BinaryString `xml:"BinaryString"`
}

type ExternalAuthenticateResponse struct {
	XMLName         xml.Name                 `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 ExternalAuthenticateResponse"`
	Status          connectorcommon50.Status `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	SignatureObject *core.SignatureObject    `xml:"urn:oasis:names:tc:dss:1.0:core:schema SignatureObject,omitempty"`
}

type StopSignature struct {
	XMLName   xml.Name                   `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 StopSignature"`
	Context   connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	JobNumber JobNumber                  `xml:"JobNumber"`
}

type StopSignatureResponse struct {
	XMLName xml.Name                 `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 StopSignatureResponse"`
	Status  connectorcommon50.Status `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
}

type TvMode string

type JobNumber string

type ViewerInfo struct {
	XMLName        xml.Name `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 ViewerInfo"`
	XslStyleSheets *struct {
		XMLName       xml.Name                          `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 XslStyleSheets"`
		XslStylesheet []connectorcommon50.XslStylesheet `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 XslStylesheet"`
	} `xml:"XslStyleSheets,omitempty"`
}

type Deselected string

type SignatureForm string

type IncludeEContent bool

type IncludeRevocationInfo bool

type Document struct {
	XMLName    xml.Name         `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 Document"`
	Id         string           `xml:"ID,attr,omitempty"`
	RefURI     string           `xml:"RefURI,attr,omitempty"`
	RefType    string           `xml:"RefType,attr,omitempty"`
	SchemaRefs string           `xml:"SchemaRefs,attr,omitempty"`
	ShortText  string           `xml:"ShortText,attr,omitempty"`
	Base64XML  string           `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Base64XML,omitempty"`
	Base64Data *core.Base64Data `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data,omitempty"`
}

type BinaryString struct {
	XMLName    xml.Name        `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 BinaryString"`
	Id         string          `xml:"ID,attr,omitempty"`
	RefURI     string          `xml:"RefURI,attr,omitempty"`
	RefType    string          `xml:"RefType,attr,omitempty"`
	SchemaRefs string          `xml:"SchemaRefs,attr,omitempty"`
	Base64Data core.Base64Data `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data"`
}

type ShortText string

type CounterSignatureMarker struct {
	XMLName                 xml.Name `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 CounterSignatureMarker"`
	SignatureValueReference []struct {
		XMLName xml.Name `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 SignatureValueReference"`
		IdRef   string   `xml:"IdRef,attr,omitempty"`
	} `xml:"SignatureValueReference"`
}

type DisplayableAttributes struct {
	XMLName              xml.Name `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 DisplayableAttributes"`
	DisplayableAttribute []struct {
		XMLName xml.Name `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 DisplayableAttribute"`
		Key     string   `xml:"Key"`
		Value   string   `xml:"Value"`
	} `xml:"DisplayableAttribute"`
}

type ReferenceToSignerCertificate bool

type DocumentType struct {
	Id         string           `xml:"ID,attr,omitempty"`
	RefURI     string           `xml:"RefURI,attr,omitempty"`
	RefType    string           `xml:"RefType,attr,omitempty"`
	SchemaRefs string           `xml:"SchemaRefs,attr,omitempty"`
	ShortText  string           `xml:"ShortText,attr,omitempty"`
	Base64XML  string           `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Base64XML,omitempty"`
	Base64Data *core.Base64Data `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data,omitempty"`
}

// extends #/components/schemas/de.gematik.ws.conn.ConnectorCommon50/DocumentType
func (DocumentType) IsConnectorCommon50DocumentType() {}

// extends #/components/schemas/oasis.names.tc.dss10.core/DocumentBaseType
func (DocumentType) IsCoreDocumentBaseType() {}

// Interface for types that extend DocumentType
type IDocumentType interface {
	IsSignatureService74DocumentType()
}

// The type itself implements IDocumentType
func (DocumentType) IsSignatureService74DocumentType() {}

type BinaryDocumentType struct {
	Id         string          `xml:"ID,attr,omitempty"`
	RefURI     string          `xml:"RefURI,attr,omitempty"`
	RefType    string          `xml:"RefType,attr,omitempty"`
	SchemaRefs string          `xml:"SchemaRefs,attr,omitempty"`
	Base64Data core.Base64Data `xml:"urn:oasis:names:tc:dss:1.0:core:schema Base64Data"`
}

// extends #/components/schemas/oasis.names.tc.dss10.core/DocumentBaseType
func (BinaryDocumentType) IsCoreDocumentBaseType() {}

// Interface for types that extend BinaryDocumentType
type IBinaryDocumentType interface {
	IsSignatureService74BinaryDocumentType()
}

// The type itself implements IBinaryDocumentType
func (BinaryDocumentType) IsSignatureService74BinaryDocumentType() {}

type VerificationResultType struct {
	HighLevelResult string `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 HighLevelResult"`
	TimestampType   string `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 TimestampType"`
	Timestamp       string `xml:"http://ws.gematik.de/conn/SignatureService/v7.4 Timestamp"`
}
