<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://example.org/global-elements"
           targetNamespace="http://example.org/global-elements"
           elementFormDefault="qualified">

<xsd:element name="Value1" type="tns:Value1"/>

<xsd:complexType name="Value1">
    <xsd:attribute name="value1" type="xsd:boolean"/>
</xsd:complexType>

<xsd:element name="Value2" type="tns:Value2Type"/>

<xsd:complexType name="Value2Type">
    <xsd:attribute name="value2" type="xsd:string"/>
</xsd:complexType>

<xsd:element name="Value3">
    <xsd:complexType>
        <xsd:attribute name="value3" type="xsd:string"/>
    </xsd:complexType>
</xsd:element>

<xsd:element name="Value4" type="tns:Value4Type"/>

<xsd:simpleType name="Value4Type">
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="\d{4}"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:element name="Value5">
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:enumeration value="Red"/>
        <xsd:enumeration value="Green"/>
        <xsd:enumeration value="Blue"/>
      </xsd:restriction>
    </xsd:simpleType>
</xsd:element>

<xsd:element name="Value6" type="xsd:anyType"/>

<xsd:element name="Slot" type="tns:SlotType"/>

<xsd:complexType name="SlotType">
    <xsd:attribute name="slot" type="xsd:string"/>
    <xsd:attribute name="value" type="xsd:string"/>
</xsd:complexType>

<xsd:element name="Slots">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element ref="tns:Slot" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>

<xsd:element name="Name" type="tns:InternationalStringType"/>
 
<xsd:complexType name="InternationalStringType">
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="tns:LocalizedString"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:element name="LocalizedString">
    <xsd:complexType>
        <xsd:attribute name="value" type="xsd:string" use="required"/>
        <xsd:attribute name="lang" type="xsd:language" use="required"/>
    </xsd:complexType>
</xsd:element>


</xsd:schema>