// Code generated by wsdl2openapi; DO NOT EDIT.
package demo.demo.greeting

import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "HelloResponse",
  namespace = "urn:demo:greeting:v1",
)
data class HelloResponse(
  @XmlElement(true)
  @XmlSerialName("Message")
  val message: String? = null,
)
