// Code generated by wsdl2openapi; DO NOT EDIT.

pub mod soap11port;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct Echo {
    #[serde(rename(serialize = "echo:Text", deserialize = "Text"))]
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct EchoResponse {
    #[serde(rename(serialize = "echo:Text", deserialize = "Text"))]
    pub text: String,
}
