// Code generated by wsdl2openapi; DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct InputDocuments {
    #[serde(
        rename(serialize = "dss10core:Document", deserialize = "Document"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub document: Vec<Document>,
    #[serde(
        rename(serialize = "dss10core:TransformedData", deserialize = "TransformedData"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub transformed_data: Vec<TransformedData>,
    #[serde(
        rename(serialize = "dss10core:DocumentHash", deserialize = "DocumentHash"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub document_hash: Vec<DocumentHash>,
    #[serde(
        rename(serialize = "dss10core:Other", deserialize = "Other"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub other: Vec<AnyType>,
}

pub type Document = DocumentType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct Base64Data {
    #[serde(rename = "@MimeType", default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    #[serde(rename = "$text")]
    pub char_data: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TransformedData {
    #[serde(rename = "@ID", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "@RefURI", default, skip_serializing_if = "Option::is_none")]
    pub ref_uri: Option<String>,
    #[serde(rename = "@RefType", default, skip_serializing_if = "Option::is_none")]
    pub ref_type: Option<String>,
    #[serde(rename = "@SchemaRefs", default, skip_serializing_if = "Option::is_none")]
    pub schema_refs: Option<String>,
    #[serde(
        rename = "@WhichReference",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub which_reference: Option<i64>,
    #[serde(
        rename(serialize = "ns-xmldsig:Transforms", deserialize = "Transforms"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub transforms: Option<crate::kon::w3200009::xmldsig::Transforms>,
    #[serde(rename(serialize = "dss10core:Base64Data", deserialize = "Base64Data"))]
    pub base64_data: Base64Data,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct DocumentHash {
    #[serde(rename = "@ID", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "@RefURI", default, skip_serializing_if = "Option::is_none")]
    pub ref_uri: Option<String>,
    #[serde(rename = "@RefType", default, skip_serializing_if = "Option::is_none")]
    pub ref_type: Option<String>,
    #[serde(rename = "@SchemaRefs", default, skip_serializing_if = "Option::is_none")]
    pub schema_refs: Option<String>,
    #[serde(
        rename = "@WhichReference",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub which_reference: Option<i64>,
    #[serde(
        rename(serialize = "ns-xmldsig:Transforms", deserialize = "Transforms"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub transforms: Option<crate::kon::w3200009::xmldsig::Transforms>,
    #[serde(
        rename(serialize = "ns-xmldsig:DigestMethod", deserialize = "DigestMethod"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub digest_method: Option<crate::kon::w3200009::xmldsig::DigestMethod>,
    #[serde(rename(serialize = "ns-xmldsig:DigestValue", deserialize = "DigestValue"))]
    pub digest_value: crate::kon::soap::Base64Binary,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SignatureObject {
    #[serde(rename = "@SchemaRefs", default, skip_serializing_if = "Option::is_none")]
    pub schema_refs: Option<String>,
    #[serde(
        rename(serialize = "ns-xmldsig:Signature", deserialize = "Signature"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub signature: Option<crate::kon::w3200009::xmldsig::Signature>,
    #[serde(
        rename(serialize = "dss10core:Timestamp", deserialize = "Timestamp"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub timestamp: Option<Timestamp>,
    #[serde(
        rename(serialize = "dss10core:Base64Signature", deserialize = "Base64Signature"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub base64_signature: Option<Base64Signature>,
    #[serde(
        rename(serialize = "dss10core:SignaturePtr", deserialize = "SignaturePtr"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub signature_ptr: Option<SignaturePtr>,
    #[serde(
        rename(serialize = "dss10core:Other", deserialize = "Other"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub other: Option<AnyType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct Base64Signature {
    #[serde(rename = "@Type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "$text")]
    pub char_data: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SignaturePtr {
    #[serde(rename = "@WhichDocument", default, skip_serializing_if = "Option::is_none")]
    pub which_document: Option<String>,
    #[serde(rename = "@XPath", default, skip_serializing_if = "Option::is_none")]
    pub x_path: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct Result {
    #[serde(rename(serialize = "dss10core:ResultMajor", deserialize = "ResultMajor"))]
    pub result_major: String,
    #[serde(
        rename(serialize = "dss10core:ResultMinor", deserialize = "ResultMinor"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub result_minor: Option<String>,
    #[serde(
        rename(serialize = "dss10core:ResultMessage", deserialize = "ResultMessage"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub result_message: Option<InternationalStringType>,
}

pub type OptionalInputs = AnyType;

pub type OptionalOutputs = AnyType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ClaimedIdentity {
    #[serde(rename(serialize = "dss10core:Name", deserialize = "Name"))]
    pub name: crate::kon::soap::AnyXml,
    #[serde(
        rename(serialize = "dss10core:SupportingInfo", deserialize = "SupportingInfo"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub supporting_info: Option<AnyType>,
}

pub type Schemas = SchemasType;

pub type Schema = DocumentType;

pub type Response = ResponseBaseType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SignRequest {
    #[serde(rename = "@RequestID", default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    #[serde(rename = "@Profile", default, skip_serializing_if = "Option::is_none")]
    pub profile: Option<String>,
    #[serde(
        rename(serialize = "dss10core:OptionalInputs", deserialize = "OptionalInputs"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub optional_inputs: Option<OptionalInputs>,
    #[serde(
        rename(serialize = "dss10core:InputDocuments", deserialize = "InputDocuments"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub input_documents: Option<InputDocuments>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SignResponse {
    #[serde(rename = "@RequestID", default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    #[serde(rename = "@Profile")]
    pub profile: String,
    #[serde(rename(serialize = "dss10core:Result", deserialize = "Result"))]
    pub result: Result,
    #[serde(
        rename(serialize = "dss10core:OptionalOutputs", deserialize = "OptionalOutputs"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub optional_outputs: Option<OptionalOutputs>,
    #[serde(
        rename(serialize = "dss10core:SignatureObject", deserialize = "SignatureObject"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub signature_object: Option<SignatureObject>,
}

pub type AddTimestamp = UpdateSignatureInstructionType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct IntendedAudience {
    #[serde(
        rename(serialize = "dss10core:Recipient", deserialize = "Recipient"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub recipient: Vec<crate::kon::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct KeySelector {
    #[serde(
        rename(serialize = "ns-xmldsig:KeyInfo", deserialize = "KeyInfo"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub key_info: Option<crate::kon::w3200009::xmldsig::KeyInfo>,
    #[serde(
        rename(serialize = "dss10core:Other", deserialize = "Other"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub other: Option<AnyType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct Properties {
    #[serde(
        rename(
            serialize = "dss10core:SignedProperties",
            deserialize = "SignedProperties"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub signed_properties: Option<PropertiesType>,
    #[serde(
        rename(
            serialize = "dss10core:UnsignedProperties",
            deserialize = "UnsignedProperties"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub unsigned_properties: Option<PropertiesType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct Property {
    #[serde(rename(serialize = "dss10core:Identifier", deserialize = "Identifier"))]
    pub identifier: String,
    #[serde(
        rename(serialize = "dss10core:Value", deserialize = "Value"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub value: Option<AnyType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct IncludeObject {
    #[serde(rename = "@WhichDocument", default, skip_serializing_if = "Option::is_none")]
    pub which_document: Option<String>,
    #[serde(
        rename = "@hasObjectTagsAndAttributesSet",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub has_object_tags_and_attributes_set: Option<bool>,
    #[serde(rename = "@ObjId", default, skip_serializing_if = "Option::is_none")]
    pub obj_id: Option<String>,
    #[serde(
        rename = "@createReference",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub create_reference: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SignaturePlacement {
    #[serde(rename = "@WhichDocument", default, skip_serializing_if = "Option::is_none")]
    pub which_document: Option<String>,
    #[serde(
        rename = "@CreateEnvelopedSignature",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub create_enveloped_signature: Option<bool>,
    #[serde(
        rename(serialize = "dss10core:XPathAfter", deserialize = "XPathAfter"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub x_path_after: Option<String>,
    #[serde(
        rename(
            serialize = "dss10core:XPathFirstChildOf",
            deserialize = "XPathFirstChildOf"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub x_path_first_child_of: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct DocumentWithSignature {
    #[serde(rename(serialize = "dss10core:Document", deserialize = "Document"))]
    pub document: Document,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SignedReferences {
    #[serde(
        rename(serialize = "dss10core:SignedReference", deserialize = "SignedReference"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub signed_reference: Vec<SignedReference>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SignedReference {
    #[serde(rename = "@WhichDocument")]
    pub which_document: String,
    #[serde(rename = "@RefURI", default, skip_serializing_if = "Option::is_none")]
    pub ref_uri: Option<String>,
    #[serde(rename = "@RefId", default, skip_serializing_if = "Option::is_none")]
    pub ref_id: Option<String>,
    #[serde(
        rename(serialize = "ns-xmldsig:Transforms", deserialize = "Transforms"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub transforms: Option<crate::kon::w3200009::xmldsig::Transforms>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct VerifyRequest {
    #[serde(rename = "@RequestID", default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    #[serde(rename = "@Profile", default, skip_serializing_if = "Option::is_none")]
    pub profile: Option<String>,
    #[serde(
        rename(serialize = "dss10core:OptionalInputs", deserialize = "OptionalInputs"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub optional_inputs: Option<OptionalInputs>,
    #[serde(
        rename(serialize = "dss10core:InputDocuments", deserialize = "InputDocuments"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub input_documents: Option<InputDocuments>,
    #[serde(
        rename(serialize = "dss10core:SignatureObject", deserialize = "SignatureObject"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub signature_object: Option<SignatureObject>,
}

pub type VerifyResponse = ResponseBaseType;

pub type VerifyManifestResults = VerifyManifestResultsType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ManifestResult {
    #[serde(
        rename(serialize = "dss10core:ReferenceXpath", deserialize = "ReferenceXpath")
    )]
    pub reference_xpath: String,
    #[serde(rename(serialize = "dss10core:Status", deserialize = "Status"))]
    pub status: String,
}

pub type AdditionalTimeInfo = AdditionalTimeInfoType;

pub type VerificationTimeInfo = VerificationTimeInfoType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct AdditionalKeyInfo {
    #[serde(rename(serialize = "ns-xmldsig:KeyInfo", deserialize = "KeyInfo"))]
    pub key_info: crate::kon::w3200009::xmldsig::KeyInfo,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ProcessingDetails {
    #[serde(
        rename(serialize = "dss10core:ValidDetail", deserialize = "ValidDetail"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub valid_detail: Vec<DetailType>,
    #[serde(
        rename(
            serialize = "dss10core:IndeterminateDetail",
            deserialize = "IndeterminateDetail"
        ),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub indeterminate_detail: Vec<DetailType>,
    #[serde(
        rename(serialize = "dss10core:InvalidDetail", deserialize = "InvalidDetail"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub invalid_detail: Vec<DetailType>,
}

pub type SigningTimeInfo = SigningTimeInfoType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ReturnUpdatedSignature {
    #[serde(rename = "@Type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

pub type UpdatedSignature = UpdatedSignatureType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ReturnTransformedDocument {
    #[serde(rename = "@WhichReference")]
    pub which_reference: i64,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TransformedDocument {
    #[serde(rename = "@WhichReference")]
    pub which_reference: i64,
    #[serde(rename(serialize = "dss10core:Document", deserialize = "Document"))]
    pub document: Document,
}

pub type ReturnTimestampedSignature = UpdateSignatureInstructionType;

pub type TimestampedSignature = UpdatedSignatureType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct Timestamp {
    #[serde(
        rename(serialize = "ns-xmldsig:Signature", deserialize = "Signature"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub signature: Option<crate::kon::w3200009::xmldsig::Signature>,
    #[serde(
        rename(
            serialize = "dss10core:RFC3161TimeStampToken",
            deserialize = "RFC3161TimeStampToken"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub rfc3161_time_stamp_token: Option<crate::kon::soap::Base64Binary>,
    #[serde(
        rename(serialize = "dss10core:Other", deserialize = "Other"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub other: Option<AnyType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TstInfo {
    #[serde(rename(serialize = "dss10core:SerialNumber", deserialize = "SerialNumber"))]
    pub serial_number: i64,
    #[serde(rename(serialize = "dss10core:CreationTime", deserialize = "CreationTime"))]
    pub creation_time: String,
    #[serde(
        rename(serialize = "dss10core:Policy", deserialize = "Policy"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub policy: Option<String>,
    #[serde(
        rename(serialize = "dss10core:ErrorBound", deserialize = "ErrorBound"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub error_bound: Option<String>,
    #[serde(
        rename(serialize = "dss10core:Ordered", deserialize = "Ordered"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ordered: Option<bool>,
    #[serde(
        rename(serialize = "dss10core:TSA", deserialize = "TSA"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub tsa: Option<crate::kon::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct RequesterIdentity {
    #[serde(rename(serialize = "dss10core:Name", deserialize = "Name"))]
    pub name: crate::kon::soap::AnyXml,
    #[serde(
        rename(serialize = "dss10core:SupportingInfo", deserialize = "SupportingInfo"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub supporting_info: Option<AnyType>,
}

pub type AttachmentReference = AttachmentReferenceType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct AnyType {
    #[serde(rename = "unknownContent", default, skip_serializing_if = "Option::is_none")]
    pub unknown_content: Option<crate::kon::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct InternationalStringType {
    #[serde(rename = "@xml:lang", default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(rename = "$text")]
    pub char_data: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct DocumentBaseType {
    #[serde(rename = "@ID", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "@RefURI", default, skip_serializing_if = "Option::is_none")]
    pub ref_uri: Option<String>,
    #[serde(rename = "@RefType", default, skip_serializing_if = "Option::is_none")]
    pub ref_type: Option<String>,
    #[serde(rename = "@SchemaRefs", default, skip_serializing_if = "Option::is_none")]
    pub schema_refs: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct DocumentType {
    #[serde(rename = "@ID", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "@RefURI", default, skip_serializing_if = "Option::is_none")]
    pub ref_uri: Option<String>,
    #[serde(rename = "@RefType", default, skip_serializing_if = "Option::is_none")]
    pub ref_type: Option<String>,
    #[serde(rename = "@SchemaRefs", default, skip_serializing_if = "Option::is_none")]
    pub schema_refs: Option<String>,
    #[serde(
        rename(serialize = "dss10core:InlineXML", deserialize = "InlineXML"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub inline_xml: Option<InlineXmlType>,
    #[serde(
        rename(serialize = "dss10core:Base64XML", deserialize = "Base64XML"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub base64_xml: Option<crate::kon::soap::Base64Binary>,
    #[serde(
        rename(serialize = "dss10core:EscapedXML", deserialize = "EscapedXML"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub escaped_xml: Option<String>,
    #[serde(
        rename(serialize = "dss10core:Base64Data", deserialize = "Base64Data"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub base64_data: Option<Base64Data>,
    #[serde(
        rename(
            serialize = "dss10core:AttachmentReference",
            deserialize = "AttachmentReference"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub attachment_reference: Option<AttachmentReference>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct InlineXmlType {
    #[serde(rename = "@ignorePIs", default, skip_serializing_if = "Option::is_none")]
    pub ignore_processing_instructions: Option<bool>,
    #[serde(
        rename = "@ignoreComments",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ignore_comments: Option<bool>,
    #[serde(rename = "unknownContent", default, skip_serializing_if = "Option::is_none")]
    pub unknown_content: Option<crate::kon::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SchemasType {
    #[serde(
        rename(serialize = "dss10core:Schema", deserialize = "Schema"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub schema: Vec<Schema>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct RequestBaseType {
    #[serde(rename = "@RequestID", default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    #[serde(rename = "@Profile", default, skip_serializing_if = "Option::is_none")]
    pub profile: Option<String>,
    #[serde(
        rename(serialize = "dss10core:OptionalInputs", deserialize = "OptionalInputs"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub optional_inputs: Option<OptionalInputs>,
    #[serde(
        rename(serialize = "dss10core:InputDocuments", deserialize = "InputDocuments"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub input_documents: Option<InputDocuments>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ResponseBaseType {
    #[serde(rename = "@RequestID", default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    #[serde(rename = "@Profile")]
    pub profile: String,
    #[serde(rename(serialize = "dss10core:Result", deserialize = "Result"))]
    pub result: Result,
    #[serde(
        rename(serialize = "dss10core:OptionalOutputs", deserialize = "OptionalOutputs"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub optional_outputs: Option<OptionalOutputs>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TimeSignatureInstructionType {
    #[serde(rename = "@Type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(
        rename = "@TimeStampTheGivenSignature",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub time_stamp_the_given_signature: Option<bool>,
    #[serde(rename = "$text")]
    pub char_data: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct UpdateSignatureInstructionType {
    #[serde(rename = "@Type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct PropertiesType {
    #[serde(
        rename(serialize = "dss10core:Property", deserialize = "Property"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub property: Vec<Property>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct VerifyManifestResultsType {
    #[serde(
        rename(serialize = "dss10core:ManifestResult", deserialize = "ManifestResult"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub manifest_result: Vec<ManifestResult>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct UseVerificationTimeType {
    #[serde(
        rename(serialize = "dss10core:CurrentTime", deserialize = "CurrentTime"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub current_time: Option<crate::kon::soap::AnyXml>,
    #[serde(
        rename(serialize = "dss10core:SpecificTime", deserialize = "SpecificTime"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub specific_time: Option<String>,
    #[serde(rename = "unknownContent", default, skip_serializing_if = "Option::is_none")]
    pub unknown_content: Option<crate::kon::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct AdditionalTimeInfoType {
    #[serde(rename = "@Type")]
    pub r#type: String,
    #[serde(rename = "@Ref", default, skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    #[serde(rename = "$text")]
    pub char_data: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct VerificationTimeInfoType {
    #[serde(
        rename(
            serialize = "dss10core:VerificationTime",
            deserialize = "VerificationTime"
        )
    )]
    pub verification_time: String,
    #[serde(
        rename(
            serialize = "dss10core:AdditionalTimeInfo",
            deserialize = "AdditionalTimeInfo"
        ),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub additional_time_info: Vec<AdditionalTimeInfo>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct DetailType {
    #[serde(rename = "@Type")]
    pub r#type: String,
    #[serde(
        rename(serialize = "dss10core:Code", deserialize = "Code"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub code: Option<String>,
    #[serde(
        rename(serialize = "dss10core:Message", deserialize = "Message"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub message: Option<InternationalStringType>,
    #[serde(rename = "unknownContent", default, skip_serializing_if = "Option::is_none")]
    pub unknown_content: Option<crate::kon::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SigningTimeInfoType {
    #[serde(rename(serialize = "dss10core:SigningTime", deserialize = "SigningTime"))]
    pub signing_time: String,
    #[serde(
        rename(
            serialize = "dss10core:SigningTimeBoundaries",
            deserialize = "SigningTimeBoundaries"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub signing_time_boundaries: Option<SigningTimeInfoTypeSigningTimeBoundaries>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct UpdatedSignatureType {
    #[serde(rename = "@Type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(
        rename(serialize = "dss10core:SignatureObject", deserialize = "SignatureObject")
    )]
    pub signature_object: SignatureObject,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct AttachmentReferenceType {
    #[serde(rename = "@AttRefURI", default, skip_serializing_if = "Option::is_none")]
    pub att_ref_uri: Option<String>,
    #[serde(rename = "@MimeType", default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    #[serde(rename(serialize = "ns-xmldsig:DigestMethod", deserialize = "DigestMethod"))]
    pub digest_method: crate::kon::w3200009::xmldsig::DigestMethod,
    #[serde(rename(serialize = "ns-xmldsig:DigestValue", deserialize = "DigestValue"))]
    pub digest_value: crate::kon::soap::Base64Binary,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct SigningTimeInfoTypeSigningTimeBoundaries {
    #[serde(
        rename(serialize = "dss10core:LowerBoundary", deserialize = "LowerBoundary"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub lower_boundary: Option<String>,
    #[serde(
        rename(serialize = "dss10core:UpperBoundary", deserialize = "UpperBoundary"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub upper_boundary: Option<String>,
}
