// Code generated by wsdl2openapi; DO NOT EDIT.

package xdsb2007

import (
	"encoding/xml"
	lcm30 "github.com/test/testproj/epa/soap/oasis/names/tc/ebxmlregrep/lcm30"
	rim30 "github.com/test/testproj/epa/soap/oasis/names/tc/ebxmlregrep/rim30"
	rs30 "github.com/test/testproj/epa/soap/oasis/names/tc/ebxmlregrep/rs30"
)

type RetrieveDocumentSetRequest struct {
	XMLName         xml.Name `xml:"urn:ihe:iti:xds-b:2007 RetrieveDocumentSetRequest"`
	DocumentRequest []struct {
		XMLName            xml.Name        `xml:"urn:ihe:iti:xds-b:2007 DocumentRequest"`
		HomeCommunityId    *rim30.LongName `xml:"HomeCommunityId,omitempty"`
		RepositoryUniqueId rim30.LongName  `xml:"RepositoryUniqueId"`
		DocumentUniqueId   rim30.LongName  `xml:"DocumentUniqueId"`
	} `xml:"DocumentRequest"`
}

type RetrieveDocumentSetResponse struct {
	XMLName          xml.Name              `xml:"urn:ihe:iti:xds-b:2007 RetrieveDocumentSetResponse"`
	RegistryResponse rs30.RegistryResponse `xml:"urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0 RegistryResponse"`
	DocumentResponse []struct {
		XMLName               xml.Name        `xml:"urn:ihe:iti:xds-b:2007 DocumentResponse"`
		HomeCommunityId       *rim30.LongName `xml:"HomeCommunityId,omitempty"`
		RepositoryUniqueId    rim30.LongName  `xml:"RepositoryUniqueId"`
		DocumentUniqueId      rim30.LongName  `xml:"DocumentUniqueId"`
		NewRepositoryUniqueId *rim30.LongName `xml:"NewRepositoryUniqueId,omitempty"`
		NewDocumentUniqueId   *rim30.LongName `xml:"NewDocumentUniqueId,omitempty"`
		MimeType              rim30.LongName  `xml:"mimeType"`
		Document              string          `xml:"Document"`
	} `xml:"DocumentResponse"`
}

type ProvideAndRegisterDocumentSetRequest struct {
	XMLName              xml.Name                   `xml:"urn:ihe:iti:xds-b:2007 ProvideAndRegisterDocumentSetRequest"`
	SubmitObjectsRequest lcm30.SubmitObjectsRequest `xml:"urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0 SubmitObjectsRequest"`
	Document             []struct {
		XMLName  xml.Name `xml:"urn:ihe:iti:xds-b:2007 Document"`
		Id       string   `xml:"id,attr"`
		CharData string   `xml:"chardata"`
	} `xml:"Document"`
}

type RetrieveDocumentSetRequestType struct {
	DocumentRequest []struct {
		XMLName            xml.Name        `xml:"urn:ihe:iti:xds-b:2007 DocumentRequest"`
		HomeCommunityId    *rim30.LongName `xml:"HomeCommunityId,omitempty"`
		RepositoryUniqueId rim30.LongName  `xml:"RepositoryUniqueId"`
		DocumentUniqueId   rim30.LongName  `xml:"DocumentUniqueId"`
	} `xml:"urn:ihe:iti:xds-b:2007 DocumentRequest"`
}

// Interface for types that extend RetrieveDocumentSetRequestType
type IRetrieveDocumentSetRequestType interface {
	IsXdsb2007RetrieveDocumentSetRequestType()
}

// The type itself implements IRetrieveDocumentSetRequestType
func (RetrieveDocumentSetRequestType) IsXdsb2007RetrieveDocumentSetRequestType() {}

type RetrieveDocumentSetResponseType struct {
	RegistryResponse rs30.RegistryResponse `xml:"urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0 RegistryResponse"`
	DocumentResponse []struct {
		XMLName               xml.Name        `xml:"urn:ihe:iti:xds-b:2007 DocumentResponse"`
		HomeCommunityId       *rim30.LongName `xml:"HomeCommunityId,omitempty"`
		RepositoryUniqueId    rim30.LongName  `xml:"RepositoryUniqueId"`
		DocumentUniqueId      rim30.LongName  `xml:"DocumentUniqueId"`
		NewRepositoryUniqueId *rim30.LongName `xml:"NewRepositoryUniqueId,omitempty"`
		NewDocumentUniqueId   *rim30.LongName `xml:"NewDocumentUniqueId,omitempty"`
		MimeType              rim30.LongName  `xml:"mimeType"`
		Document              string          `xml:"Document"`
	} `xml:"urn:ihe:iti:xds-b:2007 DocumentResponse"`
}

// Interface for types that extend RetrieveDocumentSetResponseType
type IRetrieveDocumentSetResponseType interface {
	IsXdsb2007RetrieveDocumentSetResponseType()
}

// The type itself implements IRetrieveDocumentSetResponseType
func (RetrieveDocumentSetResponseType) IsXdsb2007RetrieveDocumentSetResponseType() {}

type ProvideAndRegisterDocumentSetRequestType struct {
	SubmitObjectsRequest lcm30.SubmitObjectsRequest `xml:"urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0 SubmitObjectsRequest"`
	Document             []struct {
		XMLName  xml.Name `xml:"urn:ihe:iti:xds-b:2007 Document"`
		Id       string   `xml:"id,attr"`
		CharData string   `xml:"chardata"`
	} `xml:"urn:ihe:iti:xds-b:2007 Document"`
}

// Interface for types that extend ProvideAndRegisterDocumentSetRequestType
type IProvideAndRegisterDocumentSetRequestType interface {
	IsXdsb2007ProvideAndRegisterDocumentSetRequestType()
}

// The type itself implements IProvideAndRegisterDocumentSetRequestType
func (ProvideAndRegisterDocumentSetRequestType) IsXdsb2007ProvideAndRegisterDocumentSetRequestType() {
}
