// Code generated by wsdl2openapi; DO NOT EDIT.

package rmd2017

import (
	"encoding/xml"
	rim30 "github.com/test/testproj/epa/soap/oasis/names/tc/ebxmlregrep/rim30"
)

type RemoveDocumentsRequest struct {
	XMLName         xml.Name `xml:"urn:ihe:iti:rmd:2017 RemoveDocumentsRequest"`
	DocumentRequest []struct {
		XMLName            xml.Name        `xml:"urn:ihe:iti:xds-b:2007 DocumentRequest"`
		HomeCommunityId    *rim30.LongName `xml:"HomeCommunityId,omitempty"`
		RepositoryUniqueId rim30.LongName  `xml:"RepositoryUniqueId"`
		DocumentUniqueId   rim30.LongName  `xml:"DocumentUniqueId"`
	} `xml:"urn:ihe:iti:xds-b:2007 DocumentRequest"`
}
