// Code generated by wsdl2openapi; DO NOT EDIT.

pub type PostalAddresses = PostalAddressListType;

pub type PostalAddress = PostalAddressType;

pub type ElectronicAddress = ElectronicAddressType;

pub type Extension = ExtensionType;

pub type TrustServiceStatusList = TrustStatusListType;

pub type TrustServiceProviderList = TrustServiceProviderListType;

pub type SchemeInformation = TslSchemeInformationType;

pub type SchemeOperatorName = InternationalNamesType;

pub type SchemeName = InternationalNamesType;

pub type SchemeInformationUri = NonEmptyMultiLangUriListType;

pub type SchemeTypeCommunityRules = NonEmptyUriListType;

pub type PolicyOrLegalNotice = PolicyOrLegalnoticeType;

pub type NextUpdate = NextUpdateType;

pub type PointersToOtherTsl = OtherTslPointersType;

pub type OtherTslPointer = OtherTslPointerType;

pub type ServiceDigitalIdentities = ServiceDigitalIdentityListType;

pub type AdditionalInformation = AdditionalInformationType;

pub type DistributionPoints = ElectronicAddressType;

pub type TrustServiceProvider = TspType;

pub type TspInformation = TspInformationType;

pub type TspServices = TspServicesListType;

pub type TspService = TspServiceType;

pub type ServiceInformation = TspServiceInformationType;

pub type ServiceSupplyPoints = ServiceSupplyPointsType;

pub type ServiceDigitalIdentity = DigitalIdentityListType;

pub type ServiceHistory = ServiceHistoryType;

pub type ServiceHistoryInstance = ServiceHistoryInstanceType;

pub type AdditionalServiceInformation = AdditionalServiceInformationType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct InternationalNamesType {
    #[serde(
        rename(serialize = "etsi022312:Name", deserialize = "Name"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub name: Vec<MultiLangNormStringType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct MultiLangNormStringType {
    #[serde(rename = "@xml:lang", default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(rename = "$text")]
    pub char_data: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct MultiLangStringType {
    #[serde(rename = "@xml:lang", default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(rename = "$text")]
    pub char_data: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct AddressType {
    #[serde(
        rename(serialize = "etsi022312:PostalAddresses", deserialize = "PostalAddresses")
    )]
    pub postal_addresses: PostalAddresses,
    #[serde(
        rename(
            serialize = "etsi022312:ElectronicAddress",
            deserialize = "ElectronicAddress"
        )
    )]
    pub electronic_address: ElectronicAddress,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct PostalAddressListType {
    #[serde(
        rename(serialize = "etsi022312:PostalAddress", deserialize = "PostalAddress"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub postal_address: Vec<PostalAddress>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct PostalAddressType {
    #[serde(rename = "@xml:lang", default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(
        rename(serialize = "etsi022312:StreetAddress", deserialize = "StreetAddress")
    )]
    pub street_address: String,
    #[serde(rename(serialize = "etsi022312:Locality", deserialize = "Locality"))]
    pub locality: String,
    #[serde(
        rename(
            serialize = "etsi022312:StateOrProvince",
            deserialize = "StateOrProvince"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub state_or_province: Option<String>,
    #[serde(
        rename(serialize = "etsi022312:PostalCode", deserialize = "PostalCode"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub postal_code: Option<String>,
    #[serde(rename(serialize = "etsi022312:CountryName", deserialize = "CountryName"))]
    pub country_name: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ElectronicAddressType {
    #[serde(
        rename(serialize = "etsi022312:URI", deserialize = "URI"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub uri: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct AnyType {
    #[serde(rename = "unknownContent", default, skip_serializing_if = "Option::is_none")]
    pub unknown_content: Option<crate::kon::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ExtensionType {
    #[serde(rename = "@Critical")]
    pub critical: bool,
    #[serde(rename = "unknownContent", default, skip_serializing_if = "Option::is_none")]
    pub unknown_content: Option<crate::kon::soap::AnyXml>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ExtensionsListType {
    #[serde(
        rename(serialize = "etsi022312:Extension", deserialize = "Extension"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub extension: Vec<Extension>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct NonEmptyMultiLangUriType {
    #[serde(rename = "@xml:lang", default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,
    #[serde(rename = "$text")]
    pub char_data: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct NonEmptyMultiLangUriListType {
    #[serde(
        rename(serialize = "etsi022312:URI", deserialize = "URI"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub uri: Vec<NonEmptyMultiLangUriType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct NonEmptyUriListType {
    #[serde(
        rename(serialize = "etsi022312:URI", deserialize = "URI"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub uri: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TrustStatusListType {
    #[serde(rename = "@TSLTag")]
    pub tsl_tag: TslTagType,
    #[serde(rename = "@Id", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(
        rename(
            serialize = "etsi022312:SchemeInformation",
            deserialize = "SchemeInformation"
        )
    )]
    pub scheme_information: SchemeInformation,
    #[serde(
        rename(
            serialize = "etsi022312:TrustServiceProviderList",
            deserialize = "TrustServiceProviderList"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trust_service_provider_list: Option<TrustServiceProviderList>,
    #[serde(
        rename(serialize = "ns-xmldsig:Signature", deserialize = "Signature"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub signature: Option<crate::kon::w3200009::xmldsig::Signature>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TslTagType {
    HttpUriEtsiOrg02231TslTag,
}

impl TslTagType {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::HttpUriEtsiOrg02231TslTag => "http://uri.etsi.org/02231/TSLTag",
        }
    }
}

impl ::std::fmt::Display for TslTagType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl ::std::str::FromStr for TslTagType {
    type Err = crate::kon::soap::UnknownEnumValue;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "http://uri.etsi.org/02231/TSLTag" => Ok(Self::HttpUriEtsiOrg02231TslTag),
            _ => {
                Err(crate::kon::soap::UnknownEnumValue {
                    type_name: "TslTagType",
                    value: value.to_owned(),
                })
            }
        }
    }
}

impl ::serde::Serialize for TslTagType {
    fn serialize<S: ::serde::Serializer>(
        &self,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> ::serde::Deserialize<'de> for TslTagType {
    fn deserialize<D: ::serde::Deserializer<'de>>(
        deserializer: D,
    ) -> Result<Self, D::Error> {
        let value = <String as ::serde::Deserialize>::deserialize(deserializer)?;
        value.parse().map_err(::serde::de::Error::custom)
    }
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TrustServiceProviderListType {
    #[serde(
        rename(
            serialize = "etsi022312:TrustServiceProvider",
            deserialize = "TrustServiceProvider"
        ),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub trust_service_provider: Vec<TrustServiceProvider>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TslSchemeInformationType {
    #[serde(
        rename(
            serialize = "etsi022312:TSLVersionIdentifier",
            deserialize = "TSLVersionIdentifier"
        )
    )]
    pub tsl_version_identifier: i64,
    #[serde(
        rename(
            serialize = "etsi022312:TSLSequenceNumber",
            deserialize = "TSLSequenceNumber"
        )
    )]
    pub tsl_sequence_number: i64,
    #[serde(rename(serialize = "etsi022312:TSLType", deserialize = "TSLType"))]
    pub tsl_type: String,
    #[serde(
        rename(
            serialize = "etsi022312:SchemeOperatorName",
            deserialize = "SchemeOperatorName"
        )
    )]
    pub scheme_operator_name: SchemeOperatorName,
    #[serde(
        rename(
            serialize = "etsi022312:SchemeOperatorAddress",
            deserialize = "SchemeOperatorAddress"
        )
    )]
    pub scheme_operator_address: AddressType,
    #[serde(rename(serialize = "etsi022312:SchemeName", deserialize = "SchemeName"))]
    pub scheme_name: SchemeName,
    #[serde(
        rename(
            serialize = "etsi022312:SchemeInformationURI",
            deserialize = "SchemeInformationURI"
        )
    )]
    pub scheme_information_uri: SchemeInformationUri,
    #[serde(
        rename(
            serialize = "etsi022312:StatusDeterminationApproach",
            deserialize = "StatusDeterminationApproach"
        )
    )]
    pub status_determination_approach: String,
    #[serde(
        rename(
            serialize = "etsi022312:SchemeTypeCommunityRules",
            deserialize = "SchemeTypeCommunityRules"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub scheme_type_community_rules: Option<SchemeTypeCommunityRules>,
    #[serde(
        rename(
            serialize = "etsi022312:SchemeTerritory",
            deserialize = "SchemeTerritory"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub scheme_territory: Option<String>,
    #[serde(
        rename(
            serialize = "etsi022312:PolicyOrLegalNotice",
            deserialize = "PolicyOrLegalNotice"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub policy_or_legal_notice: Option<PolicyOrLegalNotice>,
    #[serde(
        rename(
            serialize = "etsi022312:HistoricalInformationPeriod",
            deserialize = "HistoricalInformationPeriod"
        )
    )]
    pub historical_information_period: i64,
    #[serde(
        rename(
            serialize = "etsi022312:PointersToOtherTSL",
            deserialize = "PointersToOtherTSL"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pointers_to_other_tsl: Option<PointersToOtherTsl>,
    #[serde(
        rename(
            serialize = "etsi022312:ListIssueDateTime",
            deserialize = "ListIssueDateTime"
        )
    )]
    pub list_issue_date_time: String,
    #[serde(rename(serialize = "etsi022312:NextUpdate", deserialize = "NextUpdate"))]
    pub next_update: NextUpdate,
    #[serde(
        rename(
            serialize = "etsi022312:DistributionPoints",
            deserialize = "DistributionPoints"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub distribution_points: Option<DistributionPoints>,
    #[serde(
        rename(
            serialize = "etsi022312:SchemeExtensions",
            deserialize = "SchemeExtensions"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub scheme_extensions: Option<ExtensionsListType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct PolicyOrLegalnoticeType {
    #[serde(
        rename(serialize = "etsi022312:TSLPolicy", deserialize = "TSLPolicy"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub tsl_policy: Vec<NonEmptyMultiLangUriType>,
    #[serde(
        rename(serialize = "etsi022312:TSLLegalNotice", deserialize = "TSLLegalNotice"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub tsl_legal_notice: Vec<MultiLangStringType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct NextUpdateType {
    #[serde(
        rename(serialize = "etsi022312:dateTime", deserialize = "dateTime"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub date_time: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct OtherTslPointersType {
    #[serde(
        rename(
            serialize = "etsi022312:OtherTSLPointer",
            deserialize = "OtherTSLPointer"
        ),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub other_tsl_pointer: Vec<OtherTslPointer>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct OtherTslPointerType {
    #[serde(
        rename(
            serialize = "etsi022312:ServiceDigitalIdentities",
            deserialize = "ServiceDigitalIdentities"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub service_digital_identities: Option<ServiceDigitalIdentities>,
    #[serde(rename(serialize = "etsi022312:TSLLocation", deserialize = "TSLLocation"))]
    pub tsl_location: String,
    #[serde(
        rename(
            serialize = "etsi022312:AdditionalInformation",
            deserialize = "AdditionalInformation"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_information: Option<AdditionalInformation>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ServiceDigitalIdentityListType {
    #[serde(
        rename(
            serialize = "etsi022312:ServiceDigitalIdentity",
            deserialize = "ServiceDigitalIdentity"
        ),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub service_digital_identity: Vec<ServiceDigitalIdentity>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct AdditionalInformationType {
    #[serde(
        rename(
            serialize = "etsi022312:TextualInformation",
            deserialize = "TextualInformation"
        ),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub textual_information: Vec<MultiLangStringType>,
    #[serde(
        rename(
            serialize = "etsi022312:OtherInformation",
            deserialize = "OtherInformation"
        ),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub other_information: Vec<AnyType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TspType {
    #[serde(
        rename(serialize = "etsi022312:TSPInformation", deserialize = "TSPInformation")
    )]
    pub tsp_information: TspInformation,
    #[serde(rename(serialize = "etsi022312:TSPServices", deserialize = "TSPServices"))]
    pub tsp_services: TspServices,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TspInformationType {
    #[serde(rename(serialize = "etsi022312:TSPName", deserialize = "TSPName"))]
    pub tsp_name: InternationalNamesType,
    #[serde(
        rename(serialize = "etsi022312:TSPTradeName", deserialize = "TSPTradeName"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub tsp_trade_name: Option<InternationalNamesType>,
    #[serde(rename(serialize = "etsi022312:TSPAddress", deserialize = "TSPAddress"))]
    pub tsp_address: AddressType,
    #[serde(
        rename(
            serialize = "etsi022312:TSPInformationURI",
            deserialize = "TSPInformationURI"
        )
    )]
    pub tsp_information_uri: NonEmptyMultiLangUriListType,
    #[serde(
        rename(
            serialize = "etsi022312:TSPInformationExtensions",
            deserialize = "TSPInformationExtensions"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub tsp_information_extensions: Option<ExtensionsListType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TspServicesListType {
    #[serde(
        rename(serialize = "etsi022312:TSPService", deserialize = "TSPService"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub tsp_service: Vec<TspService>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TspServiceType {
    #[serde(
        rename(
            serialize = "etsi022312:ServiceInformation",
            deserialize = "ServiceInformation"
        )
    )]
    pub service_information: ServiceInformation,
    #[serde(
        rename(serialize = "etsi022312:ServiceHistory", deserialize = "ServiceHistory"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub service_history: Option<ServiceHistory>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct TspServiceInformationType {
    #[serde(
        rename(
            serialize = "etsi022312:ServiceTypeIdentifier",
            deserialize = "ServiceTypeIdentifier"
        )
    )]
    pub service_type_identifier: String,
    #[serde(rename(serialize = "etsi022312:ServiceName", deserialize = "ServiceName"))]
    pub service_name: InternationalNamesType,
    #[serde(
        rename(
            serialize = "etsi022312:ServiceDigitalIdentity",
            deserialize = "ServiceDigitalIdentity"
        )
    )]
    pub service_digital_identity: ServiceDigitalIdentity,
    #[serde(
        rename(serialize = "etsi022312:ServiceStatus", deserialize = "ServiceStatus")
    )]
    pub service_status: String,
    #[serde(
        rename(
            serialize = "etsi022312:StatusStartingTime",
            deserialize = "StatusStartingTime"
        )
    )]
    pub status_starting_time: String,
    #[serde(
        rename(
            serialize = "etsi022312:SchemeServiceDefinitionURI",
            deserialize = "SchemeServiceDefinitionURI"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub scheme_service_definition_uri: Option<NonEmptyMultiLangUriListType>,
    #[serde(
        rename(
            serialize = "etsi022312:ServiceSupplyPoints",
            deserialize = "ServiceSupplyPoints"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub service_supply_points: Option<ServiceSupplyPoints>,
    #[serde(
        rename(
            serialize = "etsi022312:TSPServiceDefinitionURI",
            deserialize = "TSPServiceDefinitionURI"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub tsp_service_definition_uri: Option<NonEmptyMultiLangUriListType>,
    #[serde(
        rename(
            serialize = "etsi022312:ServiceInformationExtensions",
            deserialize = "ServiceInformationExtensions"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub service_information_extensions: Option<ExtensionsListType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ServiceSupplyPointsType {
    #[serde(
        rename(
            serialize = "etsi022312:ServiceSupplyPoint",
            deserialize = "ServiceSupplyPoint"
        ),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub service_supply_point: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct DigitalIdentityListType {
    #[serde(
        rename(serialize = "etsi022312:DigitalId", deserialize = "DigitalId"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub digital_id: Vec<DigitalIdentityType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct DigitalIdentityType {
    #[serde(
        rename(
            serialize = "etsi022312:X509Certificate",
            deserialize = "X509Certificate"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub x509_certificate: Option<crate::kon::soap::Base64Binary>,
    #[serde(
        rename(
            serialize = "etsi022312:X509SubjectName",
            deserialize = "X509SubjectName"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub x509_subject_name: Option<String>,
    #[serde(
        rename(serialize = "ns-xmldsig:KeyValue", deserialize = "KeyValue"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub key_value: Option<crate::kon::w3200009::xmldsig::KeyValue>,
    #[serde(
        rename(serialize = "etsi022312:X509SKI", deserialize = "X509SKI"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub x509_ski: Option<crate::kon::soap::Base64Binary>,
    #[serde(
        rename(serialize = "etsi022312:Other", deserialize = "Other"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub other: Option<AnyType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ServiceHistoryType {
    #[serde(
        rename(
            serialize = "etsi022312:ServiceHistoryInstance",
            deserialize = "ServiceHistoryInstance"
        ),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub service_history_instance: Vec<ServiceHistoryInstance>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ServiceHistoryInstanceType {
    #[serde(
        rename(
            serialize = "etsi022312:ServiceTypeIdentifier",
            deserialize = "ServiceTypeIdentifier"
        )
    )]
    pub service_type_identifier: String,
    #[serde(rename(serialize = "etsi022312:ServiceName", deserialize = "ServiceName"))]
    pub service_name: InternationalNamesType,
    #[serde(
        rename(
            serialize = "etsi022312:ServiceDigitalIdentity",
            deserialize = "ServiceDigitalIdentity"
        )
    )]
    pub service_digital_identity: ServiceDigitalIdentity,
    #[serde(
        rename(serialize = "etsi022312:ServiceStatus", deserialize = "ServiceStatus")
    )]
    pub service_status: String,
    #[serde(
        rename(
            serialize = "etsi022312:StatusStartingTime",
            deserialize = "StatusStartingTime"
        )
    )]
    pub status_starting_time: String,
    #[serde(
        rename(
            serialize = "etsi022312:ServiceInformationExtensions",
            deserialize = "ServiceInformationExtensions"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub service_information_extensions: Option<ExtensionsListType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct AdditionalServiceInformationType {
    #[serde(rename(serialize = "etsi022312:URI", deserialize = "URI"))]
    pub uri: NonEmptyMultiLangUriType,
    #[serde(
        rename(
            serialize = "etsi022312:InformationValue",
            deserialize = "InformationValue"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub information_value: Option<String>,
    #[serde(
        rename(
            serialize = "etsi022312:OtherInformation",
            deserialize = "OtherInformation"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub other_information: Option<AnyType>,
}
