// Code generated by wsdl2openapi; DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct Node {
    #[serde(rename = "@type")]
    pub r#type: String,
    #[serde(
        rename(serialize = "tree:Self", deserialize = "Self"),
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub self_: ::std::option::Option<String>,
    #[serde(
        rename(serialize = "tree:Parent", deserialize = "Parent"),
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub parent: ::std::option::Option<Box<Node>>,
    #[serde(
        rename(serialize = "tree:Child", deserialize = "Child"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub children: Vec<Node>,
    #[serde(
        rename(serialize = "tree:Link", deserialize = "Link"),
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub link: ::std::option::Option<Box<Link>>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct Link {
    #[serde(rename(serialize = "tree:Target", deserialize = "Target"))]
    pub target: Box<Node>,
    #[serde(
        rename = "@xml:lang",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub lang: ::std::option::Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct Option {
    #[serde(
        rename(serialize = "tree:Value", deserialize = "Value"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub values: Vec<String>,
    #[serde(
        rename(serialize = "tree:Version", deserialize = "Version"),
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub version: ::std::option::Option<Version>,
    #[serde(
        rename(serialize = "tree:Payload", deserialize = "Payload"),
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub payload: ::std::option::Option<crate::soap::Base64Binary>,
    #[serde(
        rename(serialize = "tree:Extension", deserialize = "Extension"),
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub extension: ::std::option::Option<crate::soap::AnyXml>,
    #[serde(
        rename(serialize = "tree:Count", deserialize = "Count"),
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub count: ::std::option::Option<i32>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Version {
    V10,
    V11,
    Latest,
    Latest2,
}

impl Version {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::V10 => "1.0",
            Self::V11 => "1.1",
            Self::Latest => "latest",
            Self::Latest2 => "LATEST",
        }
    }
}

impl ::std::fmt::Display for Version {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl ::std::str::FromStr for Version {
    type Err = crate::soap::UnknownEnumValue;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "1.0" => Ok(Self::V10),
            "1.1" => Ok(Self::V11),
            "latest" => Ok(Self::Latest),
            "LATEST" => Ok(Self::Latest2),
            _ => {
                Err(crate::soap::UnknownEnumValue {
                    type_name: "Version",
                    value: value.to_owned(),
                })
            }
        }
    }
}

impl ::serde::Serialize for Version {
    fn serialize<S: ::serde::Serializer>(
        &self,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> ::serde::Deserialize<'de> for Version {
    fn deserialize<D: ::serde::Deserializer<'de>>(
        deserializer: D,
    ) -> Result<Self, D::Error> {
        let value = <String as ::serde::Deserialize>::deserialize(deserializer)?;
        value.parse().map_err(::serde::de::Error::custom)
    }
}

pub type Root = Node;
