// Code generated by wsdl2openapi; DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct Hello {
    #[serde(rename(serialize = "greeting:Name", deserialize = "Name"))]
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct HelloResponse {
    #[serde(
        rename(serialize = "greeting:Message", deserialize = "Message"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub message: Option<String>,
}

/// `SOAP-ENV:Body` content of a `Hello` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum HelloInput {
    #[serde(rename(serialize = "greeting:Hello", deserialize = "Hello"))]
    Hello(Hello),
}

impl crate::soap::BodyContent for HelloInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        ("@xmlns:greeting", "urn:demo:greeting:v1"),
    ];
}

impl crate::soap::SoapRequest for HelloInput {
    const OPERATION: crate::soap::SoapOperation = crate::soap::SoapOperation {
        name: "Hello",
        soap_action: "urn:demo:greeting:v1#Hello",
        binding_type: "soap11",
        service: "",
        version: "",
        timeout: crate::soap::Timeout::Short,
    };
    type Response = HelloOutput;
}

impl From<Hello> for HelloInput {
    fn from(request: Hello) -> Self {
        Self::Hello(request)
    }
}

impl From<Hello> for crate::soap::Envelope<HelloInput> {
    fn from(request: Hello) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `Hello` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum HelloOutput {
    #[serde(rename(serialize = "greeting:HelloResponse", deserialize = "HelloResponse"))]
    HelloResponse(HelloResponse),
    #[serde(rename(serialize = "SOAP-ENV:Fault", deserialize = "Fault"))]
    Fault(crate::soap::Fault<crate::soap::NoDetail>),
}

impl crate::soap::BodyContent for HelloOutput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        ("@xmlns:greeting", "urn:demo:greeting:v1"),
    ];
}

impl crate::soap::SoapResponse for HelloOutput {
    type Success = HelloResponse;
    type Detail = crate::soap::NoDetail;
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
    #[allow(clippy::result_large_err)]
    fn into_result(
        self,
    ) -> Result<HelloResponse, crate::soap::Fault<crate::soap::NoDetail>> {
        match self {
            Self::HelloResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

pub type HelloEnvelope = crate::soap::Envelope<HelloInput>;

pub type HelloResponseEnvelope = crate::soap::Envelope<HelloOutput>;

/// Operations of the `GreetingPort` port, to be implemented over a SOAP transport.
pub trait GreetingPort {
    type Error;
    fn hello(
        &self,
        request: Hello,
    ) -> impl ::std::future::Future<Output = Result<HelloResponse, Self::Error>> + Send;
}
