// Code generated by wsdl2openapi; DO NOT EDIT.

/// `SOAP-ENV:Body` content of a `ExternalAuthenticate` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum ExternalAuthenticateInput {
    #[serde(
        rename(
            serialize = "signatureservice74:ExternalAuthenticate",
            deserialize = "ExternalAuthenticate"
        )
    )]
    ExternalAuthenticate(
        crate::kon::gematik::conn::signatureservice74::ExternalAuthenticate,
    ),
}

impl crate::kon::soap::BodyContent for ExternalAuthenticateInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        ("@xmlns:connectorcommon50", "http://ws.gematik.de/conn/ConnectorCommon/v5.0"),
        ("@xmlns:connectorcontext20", "http://ws.gematik.de/conn/ConnectorContext/v2.0"),
        ("@xmlns:dss10core", "urn:oasis:names:tc:dss:1.0:core:schema"),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
        ("@xmlns:ns-xmldsig", "http://www.w3.org/2000/09/xmldsig#"),
        ("@xmlns:signatureservice74", "http://ws.gematik.de/conn/SignatureService/v7.4"),
    ];
}

impl crate::kon::soap::SoapRequest for ExternalAuthenticateInput {
    const OPERATION: crate::kon::soap::SoapOperation = crate::kon::soap::SoapOperation {
        name: "ExternalAuthenticate",
        soap_action: "http://ws.gematik.de/conn/SignatureService/v7.4#ExternalAuthenticate",
        binding_type: "soap11",
        service: "",
        version: "",
        timeout: crate::kon::soap::Timeout::Short,
    };
    type Response = ExternalAuthenticateOutput;
}

impl From<crate::kon::gematik::conn::signatureservice74::ExternalAuthenticate>
for ExternalAuthenticateInput {
    fn from(
        request: crate::kon::gematik::conn::signatureservice74::ExternalAuthenticate,
    ) -> Self {
        Self::ExternalAuthenticate(request)
    }
}

impl From<crate::kon::gematik::conn::signatureservice74::ExternalAuthenticate>
for crate::kon::soap::Envelope<ExternalAuthenticateInput> {
    fn from(
        request: crate::kon::gematik::conn::signatureservice74::ExternalAuthenticate,
    ) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `ExternalAuthenticate` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum ExternalAuthenticateOutput {
    #[serde(
        rename(
            serialize = "signatureservice74:ExternalAuthenticateResponse",
            deserialize = "ExternalAuthenticateResponse"
        )
    )]
    ExternalAuthenticateResponse(
        crate::kon::gematik::conn::signatureservice74::ExternalAuthenticateResponse,
    ),
    #[serde(rename(serialize = "SOAP-ENV:Fault", deserialize = "Fault"))]
    Fault(crate::kon::soap::Fault<ExternalAuthenticateFaultDetail>),
}

impl ExternalAuthenticateOutput {
    #[allow(clippy::result_large_err)]
    pub fn into_result(
        self,
    ) -> Result<
        crate::kon::gematik::conn::signatureservice74::ExternalAuthenticateResponse,
        crate::kon::soap::Fault<ExternalAuthenticateFaultDetail>,
    > {
        match self {
            Self::ExternalAuthenticateResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

impl crate::kon::soap::BodyContent for ExternalAuthenticateOutput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        ("@xmlns:connectorcommon50", "http://ws.gematik.de/conn/ConnectorCommon/v5.0"),
        ("@xmlns:connectorcontext20", "http://ws.gematik.de/conn/ConnectorContext/v2.0"),
        ("@xmlns:dss10core", "urn:oasis:names:tc:dss:1.0:core:schema"),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
        ("@xmlns:ns-xmldsig", "http://www.w3.org/2000/09/xmldsig#"),
        ("@xmlns:signatureservice74", "http://ws.gematik.de/conn/SignatureService/v7.4"),
    ];
}

impl crate::kon::soap::SoapResponse for ExternalAuthenticateOutput {
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
}

/// Typed `detail` content of a `ExternalAuthenticate` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ExternalAuthenticateFaultDetail {
    #[serde(
        rename(serialize = "error20:Error", deserialize = "Error"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<crate::kon::gematik::tel::error20::Error>,
}

pub type ExternalAuthenticateEnvelope = crate::kon::soap::Envelope<
    ExternalAuthenticateInput,
>;

pub type ExternalAuthenticateResponseEnvelope = crate::kon::soap::Envelope<
    ExternalAuthenticateOutput,
>;

/// Operations of the `AuthSignatureServicePort` port, to be implemented over a SOAP transport.
pub trait AuthSignatureServicePort {
    type Error;
    fn external_authenticate(
        &self,
        request: crate::kon::gematik::conn::signatureservice74::ExternalAuthenticate,
    ) -> impl ::std::future::Future<
        Output = Result<
            crate::kon::gematik::conn::signatureservice74::ExternalAuthenticateResponse,
            Self::Error,
        >,
    > + Send;
}
