// Code generated by wsdl2openapi; DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct RequestCard {
    #[serde(rename(serialize = "connectorcontext20:Context", deserialize = "Context"))]
    pub context: crate::kon::gematik::conn::connectorcontext20::Context,
    #[serde(rename(serialize = "cardterminalservice11:Slot", deserialize = "Slot"))]
    pub slot: Slot,
    #[serde(
        rename(serialize = "cardservicecommon20:CardType", deserialize = "CardType"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub card_type: Option<crate::kon::gematik::conn::cardservicecommon20::CardType>,
    #[serde(
        rename(
            serialize = "cardterminalservice11:DisplayMsg",
            deserialize = "DisplayMsg"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub display_msg: Option<String>,
    #[serde(
        rename(serialize = "cardterminalservice11:TimeOut", deserialize = "TimeOut"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub time_out: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct RequestCardResponse {
    #[serde(rename(serialize = "connectorcommon50:Status", deserialize = "Status"))]
    pub status: crate::kon::gematik::conn::connectorcommon50::Status,
    #[serde(
        rename(
            serialize = "cardterminalservice11:AlreadyInserted",
            deserialize = "AlreadyInserted"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub already_inserted: Option<bool>,
    #[serde(
        rename(serialize = "cardservice81:Card", deserialize = "Card"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub card: Option<crate::kon::gematik::conn::cardservice81::Card>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct EjectCard {
    #[serde(rename(serialize = "connectorcontext20:Context", deserialize = "Context"))]
    pub context: crate::kon::gematik::conn::connectorcontext20::Context,
    #[serde(
        rename(serialize = "connectorcommon50:CardHandle", deserialize = "CardHandle"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub card_handle: Option<String>,
    #[serde(
        rename(serialize = "cardterminalservice11:Slot", deserialize = "Slot"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub slot: Option<Slot>,
    #[serde(
        rename(
            serialize = "cardterminalservice11:DisplayMsg",
            deserialize = "DisplayMsg"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub display_msg: Option<String>,
    #[serde(
        rename(serialize = "cardterminalservice11:TimeOut", deserialize = "TimeOut"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub time_out: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct EjectCardResponse {
    #[serde(rename(serialize = "connectorcommon50:Status", deserialize = "Status"))]
    pub status: crate::kon::gematik::conn::connectorcommon50::Status,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct Slot {
    #[serde(rename(serialize = "cardservicecommon20:CtId", deserialize = "CtId"))]
    pub ct_id: String,
    #[serde(rename(serialize = "cardservicecommon20:SlotId", deserialize = "SlotId"))]
    pub slot_id: i64,
}

/// `SOAP-ENV:Body` content of a `RequestCard` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum RequestCardInput {
    #[serde(
        rename(
            serialize = "cardterminalservice11:RequestCard",
            deserialize = "RequestCard"
        )
    )]
    RequestCard(RequestCard),
}

impl crate::kon::soap::BodyContent for RequestCardInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        ("@xmlns:cardservice81", "http://ws.gematik.de/conn/CardService/v8.1"),
        (
            "@xmlns:cardservicecommon20",
            "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
        ),
        (
            "@xmlns:cardterminalservice11",
            "http://ws.gematik.de/conn/CardTerminalService/v1.1",
        ),
        ("@xmlns:connectorcommon50", "http://ws.gematik.de/conn/ConnectorCommon/v5.0"),
        ("@xmlns:connectorcontext20", "http://ws.gematik.de/conn/ConnectorContext/v2.0"),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
}

impl crate::kon::soap::SoapRequest for RequestCardInput {
    const OPERATION: crate::kon::soap::SoapOperation = crate::kon::soap::SoapOperation {
        name: "RequestCard",
        soap_action: "http://ws.gematik.de/conn/CardTerminalService/v1.1#RequestCard",
        binding_type: "soap11",
    };
    type Response = RequestCardOutput;
}

impl From<RequestCard> for RequestCardInput {
    fn from(request: RequestCard) -> Self {
        Self::RequestCard(request)
    }
}

impl From<RequestCard> for crate::kon::soap::Envelope<RequestCardInput> {
    fn from(request: RequestCard) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `RequestCard` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum RequestCardOutput {
    #[serde(
        rename(
            serialize = "cardterminalservice11:RequestCardResponse",
            deserialize = "RequestCardResponse"
        )
    )]
    RequestCardResponse(RequestCardResponse),
    #[serde(rename(serialize = "SOAP-ENV:Fault", deserialize = "Fault"))]
    Fault(crate::kon::soap::Fault<RequestCardFaultDetail>),
}

impl RequestCardOutput {
    #[allow(clippy::result_large_err)]
    pub fn into_result(
        self,
    ) -> Result<RequestCardResponse, crate::kon::soap::Fault<RequestCardFaultDetail>> {
        match self {
            Self::RequestCardResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

impl crate::kon::soap::BodyContent for RequestCardOutput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        ("@xmlns:cardservice81", "http://ws.gematik.de/conn/CardService/v8.1"),
        (
            "@xmlns:cardservicecommon20",
            "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
        ),
        (
            "@xmlns:cardterminalservice11",
            "http://ws.gematik.de/conn/CardTerminalService/v1.1",
        ),
        ("@xmlns:connectorcommon50", "http://ws.gematik.de/conn/ConnectorCommon/v5.0"),
        ("@xmlns:connectorcontext20", "http://ws.gematik.de/conn/ConnectorContext/v2.0"),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
}

/// Typed `detail` content of a `RequestCard` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct RequestCardFaultDetail {
    #[serde(
        rename(serialize = "error20:Error", deserialize = "Error"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<crate::kon::gematik::tel::error20::Error>,
}

pub type RequestCardEnvelope = crate::kon::soap::Envelope<RequestCardInput>;

pub type RequestCardResponseEnvelope = crate::kon::soap::Envelope<RequestCardOutput>;

/// `SOAP-ENV:Body` content of a `EjectCard` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EjectCardInput {
    #[serde(
        rename(serialize = "cardterminalservice11:EjectCard", deserialize = "EjectCard")
    )]
    EjectCard(EjectCard),
}

impl crate::kon::soap::BodyContent for EjectCardInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:cardservicecommon20",
            "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
        ),
        (
            "@xmlns:cardterminalservice11",
            "http://ws.gematik.de/conn/CardTerminalService/v1.1",
        ),
        ("@xmlns:connectorcommon50", "http://ws.gematik.de/conn/ConnectorCommon/v5.0"),
        ("@xmlns:connectorcontext20", "http://ws.gematik.de/conn/ConnectorContext/v2.0"),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
}

impl crate::kon::soap::SoapRequest for EjectCardInput {
    const OPERATION: crate::kon::soap::SoapOperation = crate::kon::soap::SoapOperation {
        name: "EjectCard",
        soap_action: "http://ws.gematik.de/conn/CardTerminalService/v1.1#EjectCard",
        binding_type: "soap11",
    };
    type Response = EjectCardOutput;
}

impl From<EjectCard> for EjectCardInput {
    fn from(request: EjectCard) -> Self {
        Self::EjectCard(request)
    }
}

impl From<EjectCard> for crate::kon::soap::Envelope<EjectCardInput> {
    fn from(request: EjectCard) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `EjectCard` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum EjectCardOutput {
    #[serde(
        rename(
            serialize = "cardterminalservice11:EjectCardResponse",
            deserialize = "EjectCardResponse"
        )
    )]
    EjectCardResponse(EjectCardResponse),
    #[serde(rename(serialize = "SOAP-ENV:Fault", deserialize = "Fault"))]
    Fault(crate::kon::soap::Fault<EjectCardFaultDetail>),
}

impl EjectCardOutput {
    #[allow(clippy::result_large_err)]
    pub fn into_result(
        self,
    ) -> Result<EjectCardResponse, crate::kon::soap::Fault<EjectCardFaultDetail>> {
        match self {
            Self::EjectCardResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

impl crate::kon::soap::BodyContent for EjectCardOutput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:cardservicecommon20",
            "http://ws.gematik.de/conn/CardServiceCommon/v2.0",
        ),
        (
            "@xmlns:cardterminalservice11",
            "http://ws.gematik.de/conn/CardTerminalService/v1.1",
        ),
        ("@xmlns:connectorcommon50", "http://ws.gematik.de/conn/ConnectorCommon/v5.0"),
        ("@xmlns:connectorcontext20", "http://ws.gematik.de/conn/ConnectorContext/v2.0"),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
}

/// Typed `detail` content of a `EjectCard` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct EjectCardFaultDetail {
    #[serde(
        rename(serialize = "error20:Error", deserialize = "Error"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<crate::kon::gematik::tel::error20::Error>,
}

pub type EjectCardEnvelope = crate::kon::soap::Envelope<EjectCardInput>;

pub type EjectCardResponseEnvelope = crate::kon::soap::Envelope<EjectCardOutput>;

/// Operations of the `CardTerminalServicePort` port, to be implemented over a SOAP transport.
pub trait CardTerminalServicePort {
    type Error;
    fn request_card(
        &self,
        request: RequestCard,
    ) -> impl ::std::future::Future<
        Output = Result<RequestCardResponse, Self::Error>,
    > + Send;
    fn eject_card(
        &self,
        request: EjectCard,
    ) -> impl ::std::future::Future<
        Output = Result<EjectCardResponse, Self::Error>,
    > + Send;
}
