// Code generated by wsdl2openapi; DO NOT EDIT.

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct CheckCertificateExpiration {
    #[serde(
        rename(serialize = "connectorcommon50:CardHandle", deserialize = "CardHandle"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub card_handle: Option<String>,
    #[serde(rename(serialize = "connectorcontext20:Context", deserialize = "Context"))]
    pub context: crate::kon::gematik::conn::connectorcontext20::Context,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct CheckCertificateExpirationResponse {
    #[serde(rename(serialize = "connectorcommon50:Status", deserialize = "Status"))]
    pub status: crate::kon::gematik::conn::connectorcommon50::Status,
    #[serde(
        rename(
            serialize = "certificateservice60:CertificateExpiration",
            deserialize = "CertificateExpiration"
        ),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub certificate_expiration: Vec<CertificateExpirationType>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ReadCardCertificate {
    #[serde(
        rename(serialize = "connectorcommon50:CardHandle", deserialize = "CardHandle")
    )]
    pub card_handle: String,
    #[serde(rename(serialize = "connectorcontext20:Context", deserialize = "Context"))]
    pub context: crate::kon::gematik::conn::connectorcontext20::Context,
    #[serde(
        rename(
            serialize = "certificateservice60:CertRefList",
            deserialize = "CertRefList"
        )
    )]
    pub cert_ref_list: ReadCardCertificateCertRefList,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ReadCardCertificateResponse {
    #[serde(rename(serialize = "connectorcommon50:Status", deserialize = "Status"))]
    pub status: crate::kon::gematik::conn::connectorcommon50::Status,
    #[serde(
        rename(
            serialize = "certificateservicecommon20:X509DataInfoList",
            deserialize = "X509DataInfoList"
        )
    )]
    pub x509_data_info_list: crate::kon::gematik::conn::certificateservicecommon20::X509DataInfoList,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct VerifyCertificate {
    #[serde(rename(serialize = "connectorcontext20:Context", deserialize = "Context"))]
    pub context: crate::kon::gematik::conn::connectorcontext20::Context,
    #[serde(
        rename(
            serialize = "certificateservicecommon20:X509Certificate",
            deserialize = "X509Certificate"
        )
    )]
    pub x509_certificate: crate::kon::soap::Base64Binary,
    #[serde(
        rename(
            serialize = "certificateservice60:VerificationTime",
            deserialize = "VerificationTime"
        ),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub verification_time: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct VerifyCertificateResponse {
    #[serde(rename(serialize = "connectorcommon50:Status", deserialize = "Status"))]
    pub status: crate::kon::gematik::conn::connectorcommon50::Status,
    #[serde(
        rename(
            serialize = "certificateservice60:VerificationStatus",
            deserialize = "VerificationStatus"
        )
    )]
    pub verification_status: VerifyCertificateResponseVerificationStatus,
    #[serde(
        rename(serialize = "certificateservice60:RoleList", deserialize = "RoleList")
    )]
    pub role_list: VerifyCertificateResponseRoleList,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct CertificateExpirationType {
    #[serde(rename(serialize = "certificateservice60:CtID", deserialize = "CtID"))]
    pub ct_id: String,
    #[serde(
        rename(serialize = "connectorcommon50:CardHandle", deserialize = "CardHandle")
    )]
    pub card_handle: String,
    #[serde(rename(serialize = "certificateservice60:ICCSN", deserialize = "ICCSN"))]
    pub iccsn: String,
    #[serde(
        rename(
            serialize = "certificateservice60:subject_commonName",
            deserialize = "subject_commonName"
        )
    )]
    pub subject_common_name: String,
    #[serde(
        rename(
            serialize = "certificateservice60:serialNumber",
            deserialize = "serialNumber"
        )
    )]
    pub serial_number: String,
    #[serde(
        rename(serialize = "certificateservice60:validity", deserialize = "validity")
    )]
    pub validity: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VerificationResultType {
    Valid,
    Inconclusive,
    Invalid,
}

impl VerificationResultType {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Valid => "VALID",
            Self::Inconclusive => "INCONCLUSIVE",
            Self::Invalid => "INVALID",
        }
    }
}

impl ::std::fmt::Display for VerificationResultType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl ::std::str::FromStr for VerificationResultType {
    type Err = crate::kon::soap::UnknownEnumValue;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "VALID" => Ok(Self::Valid),
            "INCONCLUSIVE" => Ok(Self::Inconclusive),
            "INVALID" => Ok(Self::Invalid),
            _ => {
                Err(crate::kon::soap::UnknownEnumValue {
                    type_name: "VerificationResultType",
                    value: value.to_owned(),
                })
            }
        }
    }
}

impl ::serde::Serialize for VerificationResultType {
    fn serialize<S: ::serde::Serializer>(
        &self,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> ::serde::Deserialize<'de> for VerificationResultType {
    fn deserialize<D: ::serde::Deserializer<'de>>(
        deserializer: D,
    ) -> Result<Self, D::Error> {
        let value = <String as ::serde::Deserialize>::deserialize(deserializer)?;
        value.parse().map_err(::serde::de::Error::custom)
    }
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ReadCardCertificateCertRefList {
    #[serde(
        rename(serialize = "certificateservice60:CertRef", deserialize = "CertRef"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub cert_ref: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct VerifyCertificateResponseVerificationStatus {
    #[serde(
        rename(
            serialize = "certificateservice60:VerificationResult",
            deserialize = "VerificationResult"
        )
    )]
    pub verification_result: VerificationResultType,
    #[serde(
        rename(serialize = "error20:Error", deserialize = "Error"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<crate::kon::gematik::tel::error20::Error>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct VerifyCertificateResponseRoleList {
    #[serde(
        rename(serialize = "certificateservice60:Role", deserialize = "Role"),
        default,
        skip_serializing_if = "Vec::is_empty"
    )]
    pub role: Vec<String>,
}

/// `SOAP-ENV:Body` content of a `CheckCertificateExpiration` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum CheckCertificateExpirationInput {
    #[serde(
        rename(
            serialize = "certificateservice60:CheckCertificateExpiration",
            deserialize = "CheckCertificateExpiration"
        )
    )]
    CheckCertificateExpiration(CheckCertificateExpiration),
}

impl crate::kon::soap::BodyContent for CheckCertificateExpirationInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:certificateservice60",
            "http://ws.gematik.de/conn/CertificateService/v6.0",
        ),
        ("@xmlns:connectorcommon50", "http://ws.gematik.de/conn/ConnectorCommon/v5.0"),
        ("@xmlns:connectorcontext20", "http://ws.gematik.de/conn/ConnectorContext/v2.0"),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
}

impl crate::kon::soap::SoapRequest for CheckCertificateExpirationInput {
    const OPERATION: crate::kon::soap::SoapOperation = crate::kon::soap::SoapOperation {
        name: "CheckCertificateExpiration",
        soap_action: "http://ws.gematik.de/conn/CertificateService/v6.0#CheckCertificateExpiration",
        binding_type: "soap11",
        service: "",
        version: "",
        timeout: crate::kon::soap::Timeout::Short,
    };
    type Response = CheckCertificateExpirationOutput;
}

impl From<CheckCertificateExpiration> for CheckCertificateExpirationInput {
    fn from(request: CheckCertificateExpiration) -> Self {
        Self::CheckCertificateExpiration(request)
    }
}

impl From<CheckCertificateExpiration>
for crate::kon::soap::Envelope<CheckCertificateExpirationInput> {
    fn from(request: CheckCertificateExpiration) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `CheckCertificateExpiration` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum CheckCertificateExpirationOutput {
    #[serde(
        rename(
            serialize = "certificateservice60:CheckCertificateExpirationResponse",
            deserialize = "CheckCertificateExpirationResponse"
        )
    )]
    CheckCertificateExpirationResponse(CheckCertificateExpirationResponse),
    #[serde(rename(serialize = "SOAP-ENV:Fault", deserialize = "Fault"))]
    Fault(crate::kon::soap::Fault<CheckCertificateExpirationFaultDetail>),
}

impl crate::kon::soap::BodyContent for CheckCertificateExpirationOutput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:certificateservice60",
            "http://ws.gematik.de/conn/CertificateService/v6.0",
        ),
        ("@xmlns:connectorcommon50", "http://ws.gematik.de/conn/ConnectorCommon/v5.0"),
        ("@xmlns:connectorcontext20", "http://ws.gematik.de/conn/ConnectorContext/v2.0"),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
}

impl crate::kon::soap::SoapResponse for CheckCertificateExpirationOutput {
    type Success = CheckCertificateExpirationResponse;
    type Detail = CheckCertificateExpirationFaultDetail;
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
    #[allow(clippy::result_large_err)]
    fn into_result(
        self,
    ) -> Result<
        CheckCertificateExpirationResponse,
        crate::kon::soap::Fault<CheckCertificateExpirationFaultDetail>,
    > {
        match self {
            Self::CheckCertificateExpirationResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

/// Typed `detail` content of a `CheckCertificateExpiration` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct CheckCertificateExpirationFaultDetail {
    #[serde(
        rename(serialize = "error20:Error", deserialize = "Error"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<crate::kon::gematik::tel::error20::Error>,
}

pub type CheckCertificateExpirationEnvelope = crate::kon::soap::Envelope<
    CheckCertificateExpirationInput,
>;

pub type CheckCertificateExpirationResponseEnvelope = crate::kon::soap::Envelope<
    CheckCertificateExpirationOutput,
>;

/// `SOAP-ENV:Body` content of a `ReadCardCertificate` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum ReadCardCertificateInput {
    #[serde(
        rename(
            serialize = "certificateservice60:ReadCardCertificate",
            deserialize = "ReadCardCertificate"
        )
    )]
    ReadCardCertificate(ReadCardCertificate),
}

impl crate::kon::soap::BodyContent for ReadCardCertificateInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:certificateservice60",
            "http://ws.gematik.de/conn/CertificateService/v6.0",
        ),
        (
            "@xmlns:certificateservicecommon20",
            "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
        ),
        ("@xmlns:connectorcommon50", "http://ws.gematik.de/conn/ConnectorCommon/v5.0"),
        ("@xmlns:connectorcontext20", "http://ws.gematik.de/conn/ConnectorContext/v2.0"),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
}

impl crate::kon::soap::SoapRequest for ReadCardCertificateInput {
    const OPERATION: crate::kon::soap::SoapOperation = crate::kon::soap::SoapOperation {
        name: "ReadCardCertificate",
        soap_action: "http://ws.gematik.de/conn/CertificateService/v6.0#ReadCardCertificate",
        binding_type: "soap11",
        service: "",
        version: "",
        timeout: crate::kon::soap::Timeout::Short,
    };
    type Response = ReadCardCertificateOutput;
}

impl From<ReadCardCertificate> for ReadCardCertificateInput {
    fn from(request: ReadCardCertificate) -> Self {
        Self::ReadCardCertificate(request)
    }
}

impl From<ReadCardCertificate> for crate::kon::soap::Envelope<ReadCardCertificateInput> {
    fn from(request: ReadCardCertificate) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `ReadCardCertificate` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum ReadCardCertificateOutput {
    #[serde(
        rename(
            serialize = "certificateservice60:ReadCardCertificateResponse",
            deserialize = "ReadCardCertificateResponse"
        )
    )]
    ReadCardCertificateResponse(ReadCardCertificateResponse),
    #[serde(rename(serialize = "SOAP-ENV:Fault", deserialize = "Fault"))]
    Fault(crate::kon::soap::Fault<ReadCardCertificateFaultDetail>),
}

impl crate::kon::soap::BodyContent for ReadCardCertificateOutput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:certificateservice60",
            "http://ws.gematik.de/conn/CertificateService/v6.0",
        ),
        (
            "@xmlns:certificateservicecommon20",
            "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
        ),
        ("@xmlns:connectorcommon50", "http://ws.gematik.de/conn/ConnectorCommon/v5.0"),
        ("@xmlns:connectorcontext20", "http://ws.gematik.de/conn/ConnectorContext/v2.0"),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
}

impl crate::kon::soap::SoapResponse for ReadCardCertificateOutput {
    type Success = ReadCardCertificateResponse;
    type Detail = ReadCardCertificateFaultDetail;
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
    #[allow(clippy::result_large_err)]
    fn into_result(
        self,
    ) -> Result<
        ReadCardCertificateResponse,
        crate::kon::soap::Fault<ReadCardCertificateFaultDetail>,
    > {
        match self {
            Self::ReadCardCertificateResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

/// Typed `detail` content of a `ReadCardCertificate` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ReadCardCertificateFaultDetail {
    #[serde(
        rename(serialize = "error20:Error", deserialize = "Error"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<crate::kon::gematik::tel::error20::Error>,
}

pub type ReadCardCertificateEnvelope = crate::kon::soap::Envelope<
    ReadCardCertificateInput,
>;

pub type ReadCardCertificateResponseEnvelope = crate::kon::soap::Envelope<
    ReadCardCertificateOutput,
>;

/// `SOAP-ENV:Body` content of a `VerifyCertificate` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum VerifyCertificateInput {
    #[serde(
        rename(
            serialize = "certificateservice60:VerifyCertificate",
            deserialize = "VerifyCertificate"
        )
    )]
    VerifyCertificate(VerifyCertificate),
}

impl crate::kon::soap::BodyContent for VerifyCertificateInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:certificateservice60",
            "http://ws.gematik.de/conn/CertificateService/v6.0",
        ),
        (
            "@xmlns:certificateservicecommon20",
            "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
        ),
        ("@xmlns:connectorcommon50", "http://ws.gematik.de/conn/ConnectorCommon/v5.0"),
        ("@xmlns:connectorcontext20", "http://ws.gematik.de/conn/ConnectorContext/v2.0"),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
}

impl crate::kon::soap::SoapRequest for VerifyCertificateInput {
    const OPERATION: crate::kon::soap::SoapOperation = crate::kon::soap::SoapOperation {
        name: "VerifyCertificate",
        soap_action: "http://ws.gematik.de/conn/CertificateService/v6.0#VerifyCertificate",
        binding_type: "soap11",
        service: "",
        version: "",
        timeout: crate::kon::soap::Timeout::Short,
    };
    type Response = VerifyCertificateOutput;
}

impl From<VerifyCertificate> for VerifyCertificateInput {
    fn from(request: VerifyCertificate) -> Self {
        Self::VerifyCertificate(request)
    }
}

impl From<VerifyCertificate> for crate::kon::soap::Envelope<VerifyCertificateInput> {
    fn from(request: VerifyCertificate) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `VerifyCertificate` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum VerifyCertificateOutput {
    #[serde(
        rename(
            serialize = "certificateservice60:VerifyCertificateResponse",
            deserialize = "VerifyCertificateResponse"
        )
    )]
    VerifyCertificateResponse(VerifyCertificateResponse),
    #[serde(rename(serialize = "SOAP-ENV:Fault", deserialize = "Fault"))]
    Fault(crate::kon::soap::Fault<VerifyCertificateFaultDetail>),
}

impl crate::kon::soap::BodyContent for VerifyCertificateOutput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        (
            "@xmlns:certificateservice60",
            "http://ws.gematik.de/conn/CertificateService/v6.0",
        ),
        (
            "@xmlns:certificateservicecommon20",
            "http://ws.gematik.de/conn/CertificateServiceCommon/v2.0",
        ),
        ("@xmlns:connectorcommon50", "http://ws.gematik.de/conn/ConnectorCommon/v5.0"),
        ("@xmlns:connectorcontext20", "http://ws.gematik.de/conn/ConnectorContext/v2.0"),
        ("@xmlns:error20", "http://ws.gematik.de/tel/error/v2.0"),
    ];
}

impl crate::kon::soap::SoapResponse for VerifyCertificateOutput {
    type Success = VerifyCertificateResponse;
    type Detail = VerifyCertificateFaultDetail;
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
    #[allow(clippy::result_large_err)]
    fn into_result(
        self,
    ) -> Result<
        VerifyCertificateResponse,
        crate::kon::soap::Fault<VerifyCertificateFaultDetail>,
    > {
        match self {
            Self::VerifyCertificateResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

/// Typed `detail` content of a `VerifyCertificate` fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct VerifyCertificateFaultDetail {
    #[serde(
        rename(serialize = "error20:Error", deserialize = "Error"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub error: Option<crate::kon::gematik::tel::error20::Error>,
}

pub type VerifyCertificateEnvelope = crate::kon::soap::Envelope<VerifyCertificateInput>;

pub type VerifyCertificateResponseEnvelope = crate::kon::soap::Envelope<
    VerifyCertificateOutput,
>;

/// Operations of the `CertificateServicePort` port, to be implemented over a SOAP transport.
pub trait CertificateServicePort {
    type Error;
    fn check_certificate_expiration(
        &self,
        request: CheckCertificateExpiration,
    ) -> impl ::std::future::Future<
        Output = Result<CheckCertificateExpirationResponse, Self::Error>,
    > + Send;
    fn read_card_certificate(
        &self,
        request: ReadCardCertificate,
    ) -> impl ::std::future::Future<
        Output = Result<ReadCardCertificateResponse, Self::Error>,
    > + Send;
    fn verify_certificate(
        &self,
        request: VerifyCertificate,
    ) -> impl ::std::future::Future<
        Output = Result<VerifyCertificateResponse, Self::Error>,
    > + Send;
}
