// Code generated by wsdl2openapi. DO NOT EDIT.

package docmgmtinsurant

import "encoding/xml"

func DocumentRegistryRegistryStoredQuery() {
	// TODO: Implement SOAP operation logic
}

type DocumentRegistryRegistryStoredQueryInputEnvelope struct {
	XMLName xml.Name `xml:"http://www.w3.org/2003/05/soap-envelope Envelope"`
}
type DocumentRegistryRegistryStoredQueryOutputEnvelope struct {
	XMLName xml.Name `xml:"http://www.w3.org/2003/05/soap-envelope Envelope"`
}

func DocumentRepositoryProvideAndRegisterDocumentSetB() {
	// TODO: Implement SOAP operation logic
}

type DocumentRepositoryProvideAndRegisterDocumentSetBInputEnvelope struct {
	XMLName xml.Name `xml:"http://www.w3.org/2003/05/soap-envelope Envelope"`
}
type DocumentRepositoryProvideAndRegisterDocumentSetBOutputEnvelope struct {
	XMLName xml.Name `xml:"http://www.w3.org/2003/05/soap-envelope Envelope"`
}

func DocumentRepositoryRetrieveDocumentSet() {
	// TODO: Implement SOAP operation logic
}

type DocumentRepositoryRetrieveDocumentSetInputEnvelope struct {
	XMLName xml.Name `xml:"http://www.w3.org/2003/05/soap-envelope Envelope"`
}
type DocumentRepositoryRetrieveDocumentSetOutputEnvelope struct {
	XMLName xml.Name `xml:"http://www.w3.org/2003/05/soap-envelope Envelope"`
}

func DocumentRegistryDeleteDocumentSet() {
	// TODO: Implement SOAP operation logic
}

type DocumentRegistryDeleteDocumentSetInputEnvelope struct {
	XMLName xml.Name `xml:"http://www.w3.org/2003/05/soap-envelope Envelope"`
}
type DocumentRegistryDeleteDocumentSetOutputEnvelope struct {
	XMLName xml.Name `xml:"http://www.w3.org/2003/05/soap-envelope Envelope"`
}

func UpdateResponderRestrictedUpdateDocumentSet() {
	// TODO: Implement SOAP operation logic
}

type UpdateResponderRestrictedUpdateDocumentSetInputEnvelope struct {
	XMLName xml.Name `xml:"http://www.w3.org/2003/05/soap-envelope Envelope"`
}
type UpdateResponderRestrictedUpdateDocumentSetOutputEnvelope struct {
	XMLName xml.Name `xml:"http://www.w3.org/2003/05/soap-envelope Envelope"`
}
