// Code generated by wsdl2openapi; DO NOT EDIT.

pub type ProductInformation = ProductInformationElementType;

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ProductVersionLocal {
    #[serde(
        rename(serialize = "productinformation11:HWVersion", deserialize = "HWVersion")
    )]
    pub hw_version: String,
    #[serde(
        rename(serialize = "productinformation11:FWVersion", deserialize = "FWVersion")
    )]
    pub fw_version: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ProductVersion {
    #[serde(
        rename(serialize = "productinformation11:Local", deserialize = "Local"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub local: Option<ProductVersionLocal>,
    #[serde(
        rename(serialize = "productinformation11:Central", deserialize = "Central"),
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub central: Option<String>,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ProductTypeInformation {
    #[serde(
        rename(
            serialize = "productinformation11:ProductType",
            deserialize = "ProductType"
        )
    )]
    pub product_type: String,
    #[serde(
        rename(
            serialize = "productinformation11:ProductTypeVersion",
            deserialize = "ProductTypeVersion"
        )
    )]
    pub product_type_version: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ProductIdentification {
    #[serde(
        rename(
            serialize = "productinformation11:ProductVendorID",
            deserialize = "ProductVendorID"
        )
    )]
    pub product_vendor_id: String,
    #[serde(
        rename(
            serialize = "productinformation11:ProductCode",
            deserialize = "ProductCode"
        )
    )]
    pub product_code: String,
    #[serde(
        rename(
            serialize = "productinformation11:ProductVersion",
            deserialize = "ProductVersion"
        )
    )]
    pub product_version: ProductVersion,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ProductMiscellaneous {
    #[serde(
        rename(
            serialize = "productinformation11:ProductVendorName",
            deserialize = "ProductVendorName"
        )
    )]
    pub product_vendor_name: String,
    #[serde(
        rename(
            serialize = "productinformation11:ProductName",
            deserialize = "ProductName"
        )
    )]
    pub product_name: String,
}

#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub struct ProductInformationElementType {
    #[serde(
        rename(
            serialize = "productinformation11:InformationDate",
            deserialize = "InformationDate"
        )
    )]
    pub information_date: String,
    #[serde(
        rename(
            serialize = "productinformation11:ProductTypeInformation",
            deserialize = "ProductTypeInformation"
        )
    )]
    pub product_type_information: ProductTypeInformation,
    #[serde(
        rename(
            serialize = "productinformation11:ProductIdentification",
            deserialize = "ProductIdentification"
        )
    )]
    pub product_identification: ProductIdentification,
    #[serde(
        rename(
            serialize = "productinformation11:ProductMiscellaneous",
            deserialize = "ProductMiscellaneous"
        )
    )]
    pub product_miscellaneous: ProductMiscellaneous,
}
