// Code generated by wsdl2openapi go generator. DO NOT EDIT.

package signatureservice75

import (
	"encoding/xml"
	error20 "github.com/test/testproj/kon/api/gematik/tel/error20"
)

type VerifyDocumentEnvelope struct {
	XMLName        xml.Name        `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	VerifyDocument *VerifyDocument `xml:"Body>VerifyDocument"`
}

func (e *VerifyDocumentEnvelope) IsFault() bool {
	return false
}

type VerifyDocumentResponseEnvelope struct {
	XMLName                xml.Name                `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	VerifyDocumentResponse *VerifyDocumentResponse `xml:"Body>VerifyDocumentResponse"`
	Fault                  *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *VerifyDocumentResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

type SignDocumentEnvelope struct {
	XMLName      xml.Name      `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	SignDocument *SignDocument `xml:"Body>SignDocument"`
}

func (e *SignDocumentEnvelope) IsFault() bool {
	return false
}

type SignDocumentResponseEnvelope struct {
	XMLName              xml.Name              `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	SignDocumentResponse *SignDocumentResponse `xml:"Body>SignDocumentResponse"`
	Fault                *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *SignDocumentResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

type GetJobNumberEnvelope struct {
	XMLName      xml.Name      `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetJobNumber *GetJobNumber `xml:"Body>GetJobNumber"`
}

func (e *GetJobNumberEnvelope) IsFault() bool {
	return false
}

type GetJobNumberResponseEnvelope struct {
	XMLName              xml.Name              `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetJobNumberResponse *GetJobNumberResponse `xml:"Body>GetJobNumberResponse"`
	Fault                *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *GetJobNumberResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

type StopSignatureEnvelope struct {
	XMLName       xml.Name       `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	StopSignature *StopSignature `xml:"Body>StopSignature"`
}

func (e *StopSignatureEnvelope) IsFault() bool {
	return false
}

type StopSignatureResponseEnvelope struct {
	XMLName               xml.Name               `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	StopSignatureResponse *StopSignatureResponse `xml:"Body>StopSignatureResponse"`
	Fault                 *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *StopSignatureResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

type ActivateComfortSignatureEnvelope struct {
	XMLName                  xml.Name                  `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	ActivateComfortSignature *ActivateComfortSignature `xml:"Body>ActivateComfortSignature"`
}

func (e *ActivateComfortSignatureEnvelope) IsFault() bool {
	return false
}

type ActivateComfortSignatureResponseEnvelope struct {
	XMLName                          xml.Name                          `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	ActivateComfortSignatureResponse *ActivateComfortSignatureResponse `xml:"Body>ActivateComfortSignatureResponse"`
	Fault                            *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *ActivateComfortSignatureResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

type DeactivateComfortSignatureEnvelope struct {
	XMLName                    xml.Name                    `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	DeactivateComfortSignature *DeactivateComfortSignature `xml:"Body>DeactivateComfortSignature"`
}

func (e *DeactivateComfortSignatureEnvelope) IsFault() bool {
	return false
}

type DeactivateComfortSignatureResponseEnvelope struct {
	XMLName                            xml.Name                            `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	DeactivateComfortSignatureResponse *DeactivateComfortSignatureResponse `xml:"Body>DeactivateComfortSignatureResponse"`
	Fault                              *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *DeactivateComfortSignatureResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

type GetSignatureModeEnvelope struct {
	XMLName          xml.Name          `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetSignatureMode *GetSignatureMode `xml:"Body>GetSignatureMode"`
}

func (e *GetSignatureModeEnvelope) IsFault() bool {
	return false
}

type GetSignatureModeResponseEnvelope struct {
	XMLName                  xml.Name                  `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	GetSignatureModeResponse *GetSignatureModeResponse `xml:"Body>GetSignatureModeResponse"`
	Fault                    *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *GetSignatureModeResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}
