package generator

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"

	"github.com/dave/jennifer/jen"
)

var xmlNameEnvelope11 = jen.Id("XMLName").Qual("encoding/xml", "Name").Tag(map[string]string{"xml": "http://schemas.xmlsoap.org/soap/envelope/ Envelope"})
var xmlNameEnvelope12 = jen.Id("XMLName").Qual("encoding/xml", "Name").Tag(map[string]string{"xml": "http://www.w3.org/2003/05/soap-envelope Envelope"})

type soapContext struct {
	service *WebService
	port    *WebServicePort
	op      *OperationDefinition
	msg     *WebServiceMessage
}

func (g *Generator) GenerateSoap() error {
	if g.Api.WebServices == nil {
		return nil
	}
	ctx := &soapContext{}
	for _, ws := range g.Api.WebServices {
		ctx.service = &ws
		for _, port := range ws.Ports {
			ctx.port = &port

			portPackage := g.NamingStrategy.PackageForPort(&ws, &port)
			filename := g.NamingStrategy.FilePath(g.OutputDir, portPackage, "soap.go")

			slog.Info("Generating SOAP port", "service", ws.Name, "port", port.Name, "package", portPackage, "filename", filename)

			err := os.MkdirAll(filepath.Dir(filename), 0755)
			if err != nil {
				return err
			}

			packagePath := g.NamingStrategy.BuildPackagePath(portPackage)
			jenFile := jen.NewFilePath(packagePath)

			jenFile.HeaderComment("// Code generated by wsdl2openapi go generator. DO NOT EDIT.")

			if err := g.renderPort(jenFile, ctx); err != nil {
				return err
			}

			if err := jenFile.Save(filename); err != nil {
				return err
			}
		}
	}

	return nil
}

func (g *Generator) renderPort(jenFile *jen.File, ctx *soapContext) error {
	for _, operation := range ctx.port.Operations {
		slog.Info("Generating SOAP operation", "operation", operation.Name)
		ctx.op = &operation
		if err := g.renderOperation(jenFile, ctx); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) renderOperation(jenFile *jen.File, ctx *soapContext) error {

	if ctx.port.BindingType == SOAP11 {
		if err := g.renderEnvelopes11(jenFile, ctx); err != nil {
			return err
		}
	} else if ctx.port.BindingType == SOAP12 {
		if err := g.renderEnvelopes12(jenFile, ctx); err != nil {
			return err
		}
	} else {
		slog.Warn("Unknown SOAP binding type", "bindingType", ctx.port.BindingType)
	}

	return nil
}

func (g *Generator) renderEnvelopes11(jenFile *jen.File, ctx *soapContext) error {

	inputEnvelopeName := g.NamingStrategy.InputEnvelopeName(ctx.op)

	if len(ctx.op.Input.SOAPHeaders) > 0 {
		slog.Warn("Generator does not support SOAP headers, but operation has headers defined. Headers will be ignored.", "operation", ctx.op.Name)
	}

	qual, rawType, err := g.resolveRef(ctx.op.Input.SOAPBody)
	if err != nil {
		return fmt.Errorf("failed to resolve input SOAP body reference for operation %s: %w", ctx.op.Name, err)
	}
	pointer, err := g.parseType(qual.PackageName, rawType)
	if err != nil {
		return fmt.Errorf("failed to parse input SOAP body type for operation %s: %w", ctx.op.Name, err)
	}

	xmlTag := fmt.Sprintf("Body>%s", pointer.Xml.Name)

	jenFile.Type().Id(inputEnvelopeName).Struct(
		xmlNameEnvelope11,
		jen.Id("Body").Qual(qual.Path, qual.Name).Tag(map[string]string{"xml": xmlTag}),
	)
	jenFile.Line()

	outputEnvelopeName := g.NamingStrategy.OutputEnvelopeName(ctx.op)
	jenFile.Type().Id(outputEnvelopeName).Struct(
		xmlNameEnvelope11,
	)
	jenFile.Line()

	return nil
}

func (g *Generator) renderEnvelopes12(jenFile *jen.File, ctx *soapContext) error {
	inputEnvelopeName := g.NamingStrategy.InputEnvelopeName(ctx.op)

	jenFile.Type().Id(inputEnvelopeName).Struct(
		xmlNameEnvelope12,
	)

	outputEnvelopeName := g.NamingStrategy.OutputEnvelopeName(ctx.op)
	jenFile.Type().Id(outputEnvelopeName).Struct(
		xmlNameEnvelope12,
	)

	return nil
}
