// Code generated by wsdl2openapi; DO NOT EDIT.

package cardservice811

import (
	"encoding/xml"
	cardservicecommon20 "github.com/test/testproj/kon/api/gematik/conn/cardservicecommon20"
	connectorcommon50 "github.com/test/testproj/kon/api/gematik/conn/connectorcommon50"
	connectorcontext20 "github.com/test/testproj/kon/api/gematik/conn/connectorcontext20"
	error20 "github.com/test/testproj/kon/api/gematik/tel/error20"
)

type Cards struct {
	XMLName xml.Name `xml:"http://ws.gematik.de/conn/CardService/v8.1 Cards"`
	Card    []Card   `xml:"Card"`
}

type Card struct {
	XMLName                   xml.Name                     `xml:"http://ws.gematik.de/conn/CardService/v8.1 Card"`
	CardHandle                string                       `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	CardType                  cardservicecommon20.CardType `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CardType"`
	CardVersion               *CardInfoTypeCardVersion     `xml:"CardVersion,omitempty"`
	Iccsn                     string                       `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 Iccsn,omitempty"`
	CtId                      string                       `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CtId"`
	SlotId                    int                          `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 SlotId"`
	InsertTime                string                       `xml:"InsertTime"`
	CardHolderName            string                       `xml:"CardHolderName,omitempty"`
	Kvnr                      string                       `xml:"Kvnr,omitempty"`
	CertificateExpirationDate string                       `xml:"CertificateExpirationDate,omitempty"`
}

type VerifyPin struct {
	XMLName    xml.Name                   `xml:"http://ws.gematik.de/conn/CardService/v8.1 VerifyPin"`
	Context    connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	CardHandle string                     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	PinTyp     string                     `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinTyp"`
}

type VerifyPinResponse struct {
	XMLName   xml.Name                      `xml:"http://ws.gematik.de/conn/CardService/v8.1 VerifyPinResponse"`
	Status    connectorcommon50.Status      `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	PinResult cardservicecommon20.PinResult `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinResult"`
	LeftTries int                           `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 LeftTries,omitempty"`
}

type ChangePin struct {
	XMLName    xml.Name                   `xml:"http://ws.gematik.de/conn/CardService/v8.1 ChangePin"`
	Context    connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	CardHandle string                     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	PinTyp     string                     `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinTyp"`
}

type ChangePinResponse struct {
	XMLName   xml.Name                      `xml:"http://ws.gematik.de/conn/CardService/v8.1 ChangePinResponse"`
	Status    connectorcommon50.Status      `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	PinResult cardservicecommon20.PinResult `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinResult"`
	LeftTries int                           `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 LeftTries,omitempty"`
}

type GetPinStatus struct {
	XMLName    xml.Name                   `xml:"http://ws.gematik.de/conn/CardService/v8.1 GetPinStatus"`
	Context    connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	CardHandle string                     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	PinTyp     string                     `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinTyp"`
}

type GetPinStatusResponse struct {
	XMLName   xml.Name                 `xml:"http://ws.gematik.de/conn/CardService/v8.1 GetPinStatusResponse"`
	Status    connectorcommon50.Status `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	PinStatus PinStatusEnum            `xml:"PinStatus,omitempty"`
	LeftTries int                      `xml:"LeftTries,omitempty"`
}

type UnblockPin struct {
	XMLName    xml.Name                   `xml:"http://ws.gematik.de/conn/CardService/v8.1 UnblockPin"`
	Context    connectorcontext20.Context `xml:"http://ws.gematik.de/conn/ConnectorContext/v2.0 Context"`
	CardHandle string                     `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	PinTyp     string                     `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinTyp"`
	SetNewPin  bool                       `xml:"SetNewPin,omitempty"`
}

type UnblockPinResponse struct {
	XMLName   xml.Name                      `xml:"http://ws.gematik.de/conn/CardService/v8.1 UnblockPinResponse"`
	Status    connectorcommon50.Status      `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 Status"`
	PinResult cardservicecommon20.PinResult `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 PinResult"`
	LeftTries int                           `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 LeftTries,omitempty"`
}

type RequestCardResultEnum string

// Enum values for RequestCardResultEnum
const (
	RequestCardResultEnumError           RequestCardResultEnum = "ERROR"
	RequestCardResultEnumOk              RequestCardResultEnum = "OK"
	RequestCardResultEnumAlreadyInserted RequestCardResultEnum = "ALREADY_INSERTED"
)

type PinStatusEnum string

// Enum values for PinStatusEnum
const (
	PinStatusEnumVerified     PinStatusEnum = "VERIFIED"
	PinStatusEnumTransportPin PinStatusEnum = "TRANSPORT_PIN"
	PinStatusEnumEmptyPin     PinStatusEnum = "EMPTY_PIN"
	PinStatusEnumBlocked      PinStatusEnum = "BLOCKED"
	PinStatusEnumVerifiable   PinStatusEnum = "VERIFIABLE"
)

type CommonStepsEnum string

// Enum values for CommonStepsEnum
const (
	CommonStepsEnumCheckCardHandle          CommonStepsEnum = "CheckCardHandle"
	CommonStepsEnumVerifyPin                CommonStepsEnum = "VerifyPin"
	CommonStepsEnumVerifyEhcPin             CommonStepsEnum = "VerifyEhcPin"
	CommonStepsEnumVerifyHpcPin             CommonStepsEnum = "VerifyHpcPin"
	CommonStepsEnumVerifySmcPin             CommonStepsEnum = "VerifySmcPin"
	CommonStepsEnumWriteToEhc               CommonStepsEnum = "WriteToEhc"
	CommonStepsEnumReadFromEhc              CommonStepsEnum = "ReadFromEhc"
	CommonStepsEnumLogging                  CommonStepsEnum = "Logging"
	CommonStepsEnumCheckEhcBlocking         CommonStepsEnum = "CheckEhcBlocking"
	CommonStepsEnumFullfillAccessConditions CommonStepsEnum = "FullfillAccessConditions"
	CommonStepsEnumCardToCard               CommonStepsEnum = "CardToCard"
)

type VersionInfoType struct {
	Major    int `xml:"http://ws.gematik.de/conn/CardService/v8.1 Major"`
	Minor    int `xml:"http://ws.gematik.de/conn/CardService/v8.1 Minor"`
	Revision int `xml:"http://ws.gematik.de/conn/CardService/v8.1 Revision"`
}

type CardInfoType struct {
	CardHandle                string                       `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	CardType                  cardservicecommon20.CardType `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CardType"`
	CardVersion               *CardInfoTypeCardVersion     `xml:"http://ws.gematik.de/conn/CardService/v8.1 CardVersion,omitempty"`
	Iccsn                     string                       `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 Iccsn,omitempty"`
	CtId                      string                       `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CtId"`
	SlotId                    int                          `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 SlotId"`
	InsertTime                string                       `xml:"http://ws.gematik.de/conn/CardService/v8.1 InsertTime"`
	CardHolderName            string                       `xml:"http://ws.gematik.de/conn/CardService/v8.1 CardHolderName,omitempty"`
	Kvnr                      string                       `xml:"http://ws.gematik.de/conn/CardService/v8.1 Kvnr,omitempty"`
	CertificateExpirationDate string                       `xml:"http://ws.gematik.de/conn/CardService/v8.1 CertificateExpirationDate,omitempty"`
}

// Interface for types that extend CardInfoType
type ICardInfoType interface {
	IsCardService811CardInfoType()
}

// The type itself implements ICardInfoType
func (CardInfoType) IsCardService811CardInfoType() {}

type CardInfoErrType struct {
	CardHandle                string                       `xml:"http://ws.gematik.de/conn/ConnectorCommon/v5.0 CardHandle"`
	CardType                  cardservicecommon20.CardType `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CardType"`
	CardVersion               *CardInfoErrTypeCardVersion  `xml:"http://ws.gematik.de/conn/CardService/v8.1 CardVersion,omitempty"`
	Iccsn                     string                       `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 Iccsn,omitempty"`
	CtId                      string                       `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 CtId"`
	SlotId                    int                          `xml:"http://ws.gematik.de/conn/CardServiceCommon/v2.0 SlotId"`
	InsertTime                string                       `xml:"http://ws.gematik.de/conn/CardService/v8.1 InsertTime"`
	CardHolderName            string                       `xml:"http://ws.gematik.de/conn/CardService/v8.1 CardHolderName,omitempty"`
	Kvnr                      string                       `xml:"http://ws.gematik.de/conn/CardService/v8.1 Kvnr,omitempty"`
	CertificateExpirationDate string                       `xml:"http://ws.gematik.de/conn/CardService/v8.1 CertificateExpirationDate,omitempty"`
	Error                     *error20.Error               `xml:"http://ws.gematik.de/tel/error/v2.0 Error,omitempty"`
}

// extends #/components/schemas/de.gematik.ws.conn.CardService811/CardInfoType
func (CardInfoErrType) IsCardService811CardInfoType() {}

type CardInfoTypeCardVersion struct {
	XMLName              xml.Name         `xml:"http://ws.gematik.de/conn/CardService/v8.1 CardVersion"`
	COSVersion           VersionInfoType  `xml:"COSVersion"`
	ObjectSystemVersion  VersionInfoType  `xml:"ObjectSystemVersion"`
	CardPTPersVersion    *VersionInfoType `xml:"CardPTPersVersion,omitempty"`
	DataStructureVersion *VersionInfoType `xml:"DataStructureVersion,omitempty"`
	LoggingVersion       *VersionInfoType `xml:"LoggingVersion,omitempty"`
	ATRVersion           *VersionInfoType `xml:"ATRVersion,omitempty"`
	GDOVersion           *VersionInfoType `xml:"GDOVersion,omitempty"`
	KeyInfoVersion       *VersionInfoType `xml:"KeyInfoVersion,omitempty"`
}

type CardInfoErrTypeCardVersion struct {
	XMLName              xml.Name         `xml:"http://ws.gematik.de/conn/CardService/v8.1 CardVersion"`
	COSVersion           VersionInfoType  `xml:"COSVersion"`
	ObjectSystemVersion  VersionInfoType  `xml:"ObjectSystemVersion"`
	CardPTPersVersion    *VersionInfoType `xml:"CardPTPersVersion,omitempty"`
	DataStructureVersion *VersionInfoType `xml:"DataStructureVersion,omitempty"`
	LoggingVersion       *VersionInfoType `xml:"LoggingVersion,omitempty"`
	ATRVersion           *VersionInfoType `xml:"ATRVersion,omitempty"`
	GDOVersion           *VersionInfoType `xml:"GDOVersion,omitempty"`
	KeyInfoVersion       *VersionInfoType `xml:"KeyInfoVersion,omitempty"`
}
