// Code generated by wsdl2openapi go generator. DO NOT EDIT.

package encryptionservice611

import (
	"encoding/xml"
	error20 "github.com/test/testproj/kon/api/gematik/tel/error20"
)

type EncryptDocumentEnvelope struct {
	XMLName         xml.Name         `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	EncryptDocument *EncryptDocument `xml:"Body>EncryptDocument"`
}

func (e *EncryptDocumentEnvelope) IsFault() bool {
	return false
}

type EncryptDocumentResponseEnvelope struct {
	XMLName                 xml.Name                 `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	EncryptDocumentResponse *EncryptDocumentResponse `xml:"Body>EncryptDocumentResponse"`
	Fault                   *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *EncryptDocumentResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}

type DecryptDocumentEnvelope struct {
	XMLName         xml.Name         `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	DecryptDocument *DecryptDocument `xml:"Body>DecryptDocument"`
}

func (e *DecryptDocumentEnvelope) IsFault() bool {
	return false
}

type DecryptDocumentResponseEnvelope struct {
	XMLName                 xml.Name                 `xml:"http://schemas.xmlsoap.org/soap/envelope/ Envelope"`
	DecryptDocumentResponse *DecryptDocumentResponse `xml:"Body>DecryptDocumentResponse"`
	Fault                   *struct {
		Code   string         `xml:"faultcode"`
		String string         `xml:"faultstring"`
		Actor  string         `xml:"faultactor"`
		Detail *error20.Error `xml:"Detail>Error"`
	} `xml:"Body>Fault"`
}

func (e *DecryptDocumentResponseEnvelope) IsFault() bool {
	return e.Fault != nil
}
