// Code generated by wsdl2openapi; DO NOT EDIT.

/// `SOAP-ENV:Body` content of a `Echo` request.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
pub enum EchoInput {
    #[serde(rename(serialize = "echo:Echo", deserialize = "Echo"))]
    Echo(crate::demo::echo::Echo),
}

impl crate::soap::BodyContent for EchoInput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        ("@xmlns:echo", "urn:demo:echo:v1"),
    ];
}

impl crate::soap::SoapRequest for EchoInput {
    const OPERATION: crate::soap::SoapOperation = crate::soap::SoapOperation {
        name: "Echo",
        soap_action: "urn:demo:echo:v1#Echo",
        binding_type: "soap11",
        service: "",
        version: "",
        timeout: crate::soap::Timeout::Short,
    };
    type Response = EchoOutput;
}

impl From<crate::demo::echo::Echo> for EchoInput {
    fn from(request: crate::demo::echo::Echo) -> Self {
        Self::Echo(request)
    }
}

impl From<crate::demo::echo::Echo> for crate::soap::Envelope<EchoInput> {
    fn from(request: crate::demo::echo::Echo) -> Self {
        Self::new(request.into())
    }
}

/// `SOAP-ENV:Body` content of a `Echo` response: the result or a SOAP fault.
#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[allow(clippy::large_enum_variant)]
pub enum EchoOutput {
    #[serde(rename(serialize = "echo:EchoResponse", deserialize = "EchoResponse"))]
    EchoResponse(crate::demo::echo::EchoResponse),
    #[serde(rename(serialize = "SOAP-ENV:Fault", deserialize = "Fault"))]
    Fault(crate::soap::Fault<crate::soap::NoDetail>),
}

impl EchoOutput {
    #[allow(clippy::result_large_err)]
    pub fn into_result(
        self,
    ) -> Result<
        crate::demo::echo::EchoResponse,
        crate::soap::Fault<crate::soap::NoDetail>,
    > {
        match self {
            Self::EchoResponse(response) => Ok(response),
            Self::Fault(fault) => Err(fault),
        }
    }
}

impl crate::soap::BodyContent for EchoOutput {
    const NAMESPACES: &'static [(&'static str, &'static str)] = &[
        ("@xmlns:echo", "urn:demo:echo:v1"),
    ];
}

impl crate::soap::SoapResponse for EchoOutput {
    fn is_fault(&self) -> bool {
        matches!(self, Self::Fault(_))
    }
}

pub type EchoEnvelope = crate::soap::Envelope<EchoInput>;

pub type EchoResponseEnvelope = crate::soap::Envelope<EchoOutput>;

/// Operations of the `Soap11Port` port, to be implemented over a SOAP transport.
pub trait Soap11Port {
    type Error;
    fn echo(
        &self,
        request: crate::demo::echo::Echo,
    ) -> impl ::std::future::Future<
        Output = Result<crate::demo::echo::EchoResponse, Self::Error>,
    > + Send;
}
