// Code generated by wsdl2openapi; DO NOT EDIT.
package demo.demo.shapes

import kotlin.Double
import kotlin.String
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement
import nl.adaptivity.xmlutil.serialization.XmlSerialName

@Serializable
@XmlSerialName(
  "Square",
  namespace = "urn:demo:shapes:v1",
)
data class Square(
  @XmlElement(false)
  @XmlSerialName("id")
  val id: String? = null,
  @XmlElement(true)
  @XmlSerialName("side")
  val side: Double,
) : IShape
